# Auto-generated by PowerPlatform.Dataverse.generator — do not edit by hand.
# Re-exports all entity classes for convenient ``from Types import Account``.
from __future__ import annotations

from .account import Account

__all__ = [
    "Account",
]
