# Auto-generated by PowerPlatform.Dataverse.generator — do not edit by hand.
# Entity : account  (SchemaName: Account)
from __future__ import annotations

from typing import Any

from PowerPlatform.Dataverse.models.entity import Entity, Field, NavField


class Account(Entity, table="account", primary_key="accountid"):
    """Typed entity class for the ``account`` Dataverse table."""

    def __init__(
        self,
        *,
        accountcategorycode: int | None = None,
        accountclassificationcode: int | None = None,
        accountid: Any | None = None,
        accountnumber: str | None = None,
        accountratingcode: int | None = None,
        address1_addressid: Any | None = None,
        address1_addresstypecode: int | None = None,
        address1_city: str | None = None,
        address1_composite: str | None = None,
        address1_country: str | None = None,
        address1_county: str | None = None,
        address1_fax: str | None = None,
        address1_freighttermscode: int | None = None,
        address1_latitude: float | None = None,
        address1_line1: str | None = None,
        address1_line2: str | None = None,
        address1_line3: str | None = None,
        address1_longitude: float | None = None,
        address1_name: str | None = None,
        address1_postalcode: str | None = None,
        address1_postofficebox: str | None = None,
        address1_primarycontactname: str | None = None,
        address1_shippingmethodcode: int | None = None,
        address1_stateorprovince: str | None = None,
        address1_telephone1: str | None = None,
        address1_telephone2: str | None = None,
        address1_telephone3: str | None = None,
        address1_upszone: str | None = None,
        address1_utcoffset: int | None = None,
        address2_addressid: Any | None = None,
        address2_addresstypecode: int | None = None,
        address2_city: str | None = None,
        address2_composite: str | None = None,
        address2_country: str | None = None,
        address2_county: str | None = None,
        address2_fax: str | None = None,
        address2_freighttermscode: int | None = None,
        address2_latitude: float | None = None,
        address2_line1: str | None = None,
        address2_line2: str | None = None,
        address2_line3: str | None = None,
        address2_longitude: float | None = None,
        address2_name: str | None = None,
        address2_postalcode: str | None = None,
        address2_postofficebox: str | None = None,
        address2_primarycontactname: str | None = None,
        address2_shippingmethodcode: int | None = None,
        address2_stateorprovince: str | None = None,
        address2_telephone1: str | None = None,
        address2_telephone2: str | None = None,
        address2_telephone3: str | None = None,
        address2_upszone: str | None = None,
        address2_utcoffset: int | None = None,
        adx_createdbyipaddress: str | None = None,
        adx_createdbyusername: str | None = None,
        adx_modifiedbyipaddress: str | None = None,
        adx_modifiedbyusername: str | None = None,
        aging30: float | None = None,
        aging30_base: float | None = None,
        aging60: float | None = None,
        aging60_base: float | None = None,
        aging90: float | None = None,
        aging90_base: float | None = None,
        businesstypecode: int | None = None,
        createdby: str | None = None,
        createdbyexternalparty: str | None = None,
        createdbyexternalpartyname: str | None = None,
        createdbyexternalpartyyominame: str | None = None,
        createdbyname: str | None = None,
        createdbyyominame: str | None = None,
        createdon: str | None = None,
        createdonbehalfby: str | None = None,
        createdonbehalfbyname: str | None = None,
        createdonbehalfbyyominame: str | None = None,
        creditlimit: float | None = None,
        creditlimit_base: float | None = None,
        creditonhold: bool | None = None,
        customersizecode: int | None = None,
        customertypecode: int | None = None,
        defaultpricelevelid: str | None = None,
        defaultpricelevelidname: str | None = None,
        description: str | None = None,
        donotbulkemail: bool | None = None,
        donotbulkpostalmail: bool | None = None,
        donotemail: bool | None = None,
        donotfax: bool | None = None,
        donotphone: bool | None = None,
        donotpostalmail: bool | None = None,
        donotsendmm: bool | None = None,
        emailaddress1: str | None = None,
        emailaddress2: str | None = None,
        emailaddress3: str | None = None,
        entityimage_timestamp: int | None = None,
        entityimage_url: str | None = None,
        entityimageid: Any | None = None,
        exchangerate: float | None = None,
        fax: str | None = None,
        followemail: bool | None = None,
        ftpsiteurl: str | None = None,
        importsequencenumber: int | None = None,
        industrycode: int | None = None,
        isprivate: bool | None = None,
        lastonholdtime: str | None = None,
        lastusedincampaign: str | None = None,
        marketcap: float | None = None,
        marketcap_base: float | None = None,
        marketingonly: bool | None = None,
        masteraccountidname: str | None = None,
        masteraccountidyominame: str | None = None,
        masterid: str | None = None,
        merged: bool | None = None,
        modifiedby: str | None = None,
        modifiedbyexternalparty: str | None = None,
        modifiedbyexternalpartyname: str | None = None,
        modifiedbyexternalpartyyominame: str | None = None,
        modifiedbyname: str | None = None,
        modifiedbyyominame: str | None = None,
        modifiedon: str | None = None,
        modifiedonbehalfby: str | None = None,
        modifiedonbehalfbyname: str | None = None,
        modifiedonbehalfbyyominame: str | None = None,
        msa_managingpartnerid: str | None = None,
        msa_managingpartneridname: str | None = None,
        msa_managingpartneridyominame: str | None = None,
        msdyn_accountkpiid: str | None = None,
        msdyn_accountkpiidname: str | None = None,
        msdyn_gdproptout: bool | None = None,
        msdyn_primarytimezone: int | None = None,
        msdyn_salesaccelerationinsightid: str | None = None,
        msdyn_salesaccelerationinsightidname: str | None = None,
        msdyn_segmentid: str | None = None,
        msdyn_segmentidname: str | None = None,
        name: str | None = None,
        numberofemployees: int | None = None,
        onholdtime: int | None = None,
        opendeals: int | None = None,
        opendeals_date: str | None = None,
        opendeals_state: int | None = None,
        openrevenue: float | None = None,
        openrevenue_base: float | None = None,
        openrevenue_date: str | None = None,
        openrevenue_state: int | None = None,
        originatingleadid: str | None = None,
        originatingleadidname: str | None = None,
        originatingleadidyominame: str | None = None,
        overriddencreatedon: str | None = None,
        ownerid: str | None = None,
        owneridname: str | None = None,
        owneridtype: str | None = None,
        owneridyominame: str | None = None,
        ownershipcode: int | None = None,
        owningbusinessunit: str | None = None,
        owningbusinessunitname: str | None = None,
        owningteam: str | None = None,
        owninguser: str | None = None,
        parentaccountid: str | None = None,
        parentaccountidname: str | None = None,
        parentaccountidyominame: str | None = None,
        participatesinworkflow: bool | None = None,
        paymenttermscode: int | None = None,
        preferredappointmentdaycode: int | None = None,
        preferredappointmenttimecode: int | None = None,
        preferredcontactmethodcode: int | None = None,
        preferredequipmentid: str | None = None,
        preferredequipmentidname: str | None = None,
        preferredserviceid: str | None = None,
        preferredserviceidname: str | None = None,
        preferredsystemuserid: str | None = None,
        preferredsystemuseridname: str | None = None,
        preferredsystemuseridyominame: str | None = None,
        primarycontactid: str | None = None,
        primarycontactidname: str | None = None,
        primarycontactidyominame: str | None = None,
        primarysatoriid: str | None = None,
        primarytwitterid: str | None = None,
        processid: Any | None = None,
        revenue: float | None = None,
        revenue_base: float | None = None,
        sharesoutstanding: int | None = None,
        shippingmethodcode: int | None = None,
        sic: str | None = None,
        slaid: str | None = None,
        slainvokedid: str | None = None,
        slainvokedidname: str | None = None,
        slaname: str | None = None,
        stageid: Any | None = None,
        statecode: int | None = None,
        statuscode: int | None = None,
        stockexchange: str | None = None,
        teamsfollowed: int | None = None,
        telephone1: str | None = None,
        telephone2: str | None = None,
        telephone3: str | None = None,
        territorycode: int | None = None,
        territoryid: str | None = None,
        territoryidname: str | None = None,
        tickersymbol: str | None = None,
        timespentbymeonemailandmeetings: str | None = None,
        timezoneruleversionnumber: int | None = None,
        transactioncurrencyid: str | None = None,
        transactioncurrencyidname: str | None = None,
        traversedpath: str | None = None,
        utcconversiontimezonecode: int | None = None,
        versionnumber: int | None = None,
        websiteurl: str | None = None,
        yominame: str | None = None,
    ) -> None:
        super().__init__(**{k: v for k, v in locals().items() if k != "self" and v is not None})

    accountcategorycode                  = Field("accountcategorycode", int, schema_name="AccountCategoryCode", dataverse_type="picklist")
    accountclassificationcode            = Field("accountclassificationcode", int, schema_name="AccountClassificationCode", dataverse_type="picklist")
    accountid                            = Field("accountid", Any)  # unmapped type: ?
    accountnumber                        = Field("accountnumber", str, schema_name="AccountNumber", dataverse_type="string")
    accountratingcode                    = Field("accountratingcode", int, schema_name="AccountRatingCode", dataverse_type="picklist")
    address1_addressid                   = Field("address1_addressid", Any)  # unmapped type: ?
    address1_addresstypecode             = Field("address1_addresstypecode", int, schema_name="Address1_AddressTypeCode", dataverse_type="picklist")
    address1_city                        = Field("address1_city", str, schema_name="Address1_City", dataverse_type="string")
    address1_composite                   = Field("address1_composite", str, schema_name="Address1_Composite", dataverse_type="memo")
    address1_country                     = Field("address1_country", str, schema_name="Address1_Country", dataverse_type="string")
    address1_county                      = Field("address1_county", str, schema_name="Address1_County", dataverse_type="string")
    address1_fax                         = Field("address1_fax", str, schema_name="Address1_Fax", dataverse_type="string")
    address1_freighttermscode            = Field("address1_freighttermscode", int, schema_name="Address1_FreightTermsCode", dataverse_type="picklist")
    address1_latitude                    = Field("address1_latitude", float, schema_name="Address1_Latitude", dataverse_type="float")
    address1_line1                       = Field("address1_line1", str, schema_name="Address1_Line1", dataverse_type="string")
    address1_line2                       = Field("address1_line2", str, schema_name="Address1_Line2", dataverse_type="string")
    address1_line3                       = Field("address1_line3", str, schema_name="Address1_Line3", dataverse_type="string")
    address1_longitude                   = Field("address1_longitude", float, schema_name="Address1_Longitude", dataverse_type="float")
    address1_name                        = Field("address1_name", str, schema_name="Address1_Name", dataverse_type="string")
    address1_postalcode                  = Field("address1_postalcode", str, schema_name="Address1_PostalCode", dataverse_type="string")
    address1_postofficebox               = Field("address1_postofficebox", str, schema_name="Address1_PostOfficeBox", dataverse_type="string")
    address1_primarycontactname          = Field("address1_primarycontactname", str, schema_name="Address1_PrimaryContactName", dataverse_type="string")
    address1_shippingmethodcode          = Field("address1_shippingmethodcode", int, schema_name="Address1_ShippingMethodCode", dataverse_type="picklist")
    address1_stateorprovince             = Field("address1_stateorprovince", str, schema_name="Address1_StateOrProvince", dataverse_type="string")
    address1_telephone1                  = Field("address1_telephone1", str, schema_name="Address1_Telephone1", dataverse_type="string")
    address1_telephone2                  = Field("address1_telephone2", str, schema_name="Address1_Telephone2", dataverse_type="string")
    address1_telephone3                  = Field("address1_telephone3", str, schema_name="Address1_Telephone3", dataverse_type="string")
    address1_upszone                     = Field("address1_upszone", str, schema_name="Address1_UPSZone", dataverse_type="string")
    address1_utcoffset                   = Field("address1_utcoffset", int, schema_name="Address1_UTCOffset", dataverse_type="int")
    address2_addressid                   = Field("address2_addressid", Any)  # unmapped type: ?
    address2_addresstypecode             = Field("address2_addresstypecode", int, schema_name="Address2_AddressTypeCode", dataverse_type="picklist")
    address2_city                        = Field("address2_city", str, schema_name="Address2_City", dataverse_type="string")
    address2_composite                   = Field("address2_composite", str, schema_name="Address2_Composite", dataverse_type="memo")
    address2_country                     = Field("address2_country", str, schema_name="Address2_Country", dataverse_type="string")
    address2_county                      = Field("address2_county", str, schema_name="Address2_County", dataverse_type="string")
    address2_fax                         = Field("address2_fax", str, schema_name="Address2_Fax", dataverse_type="string")
    address2_freighttermscode            = Field("address2_freighttermscode", int, schema_name="Address2_FreightTermsCode", dataverse_type="picklist")
    address2_latitude                    = Field("address2_latitude", float, schema_name="Address2_Latitude", dataverse_type="float")
    address2_line1                       = Field("address2_line1", str, schema_name="Address2_Line1", dataverse_type="string")
    address2_line2                       = Field("address2_line2", str, schema_name="Address2_Line2", dataverse_type="string")
    address2_line3                       = Field("address2_line3", str, schema_name="Address2_Line3", dataverse_type="string")
    address2_longitude                   = Field("address2_longitude", float, schema_name="Address2_Longitude", dataverse_type="float")
    address2_name                        = Field("address2_name", str, schema_name="Address2_Name", dataverse_type="string")
    address2_postalcode                  = Field("address2_postalcode", str, schema_name="Address2_PostalCode", dataverse_type="string")
    address2_postofficebox               = Field("address2_postofficebox", str, schema_name="Address2_PostOfficeBox", dataverse_type="string")
    address2_primarycontactname          = Field("address2_primarycontactname", str, schema_name="Address2_PrimaryContactName", dataverse_type="string")
    address2_shippingmethodcode          = Field("address2_shippingmethodcode", int, schema_name="Address2_ShippingMethodCode", dataverse_type="picklist")
    address2_stateorprovince             = Field("address2_stateorprovince", str, schema_name="Address2_StateOrProvince", dataverse_type="string")
    address2_telephone1                  = Field("address2_telephone1", str, schema_name="Address2_Telephone1", dataverse_type="string")
    address2_telephone2                  = Field("address2_telephone2", str, schema_name="Address2_Telephone2", dataverse_type="string")
    address2_telephone3                  = Field("address2_telephone3", str, schema_name="Address2_Telephone3", dataverse_type="string")
    address2_upszone                     = Field("address2_upszone", str, schema_name="Address2_UPSZone", dataverse_type="string")
    address2_utcoffset                   = Field("address2_utcoffset", int, schema_name="Address2_UTCOffset", dataverse_type="int")
    adx_createdbyipaddress               = Field("adx_createdbyipaddress", str, schema_name="Adx_CreatedByIPAddress", dataverse_type="string")
    adx_createdbyusername                = Field("adx_createdbyusername", str, schema_name="Adx_CreatedByUsername", dataverse_type="string")
    adx_modifiedbyipaddress              = Field("adx_modifiedbyipaddress", str, schema_name="Adx_ModifiedByIPAddress", dataverse_type="string")
    adx_modifiedbyusername               = Field("adx_modifiedbyusername", str, schema_name="Adx_ModifiedByUsername", dataverse_type="string")
    aging30                              = Field("aging30", float, schema_name="Aging30", dataverse_type="decimal")
    aging30_base                         = Field("aging30_base", float, schema_name="Aging30_Base", dataverse_type="decimal")
    aging60                              = Field("aging60", float, schema_name="Aging60", dataverse_type="decimal")
    aging60_base                         = Field("aging60_base", float, schema_name="Aging60_Base", dataverse_type="decimal")
    aging90                              = Field("aging90", float, schema_name="Aging90", dataverse_type="decimal")
    aging90_base                         = Field("aging90_base", float, schema_name="Aging90_Base", dataverse_type="decimal")
    businesstypecode                     = Field("businesstypecode", int, schema_name="BusinessTypeCode", dataverse_type="picklist")
    createdby                            = Field("createdby", str, schema_name="CreatedBy", dataverse_type="lookup")
    createdbyexternalparty               = Field("createdbyexternalparty", str, schema_name="CreatedByExternalParty", dataverse_type="lookup")
    createdbyexternalpartyname           = Field("createdbyexternalpartyname", str, schema_name="CreatedByExternalPartyName", dataverse_type="string")
    createdbyexternalpartyyominame       = Field("createdbyexternalpartyyominame", str, schema_name="CreatedByExternalPartyYomiName", dataverse_type="string")
    createdbyname                        = Field("createdbyname", str, schema_name="CreatedByName", dataverse_type="string")
    createdbyyominame                    = Field("createdbyyominame", str, schema_name="CreatedByYomiName", dataverse_type="string")
    createdon                            = Field("createdon", str, schema_name="CreatedOn", dataverse_type="datetime")
    createdonbehalfby                    = Field("createdonbehalfby", str, schema_name="CreatedOnBehalfBy", dataverse_type="lookup")
    createdonbehalfbyname                = Field("createdonbehalfbyname", str, schema_name="CreatedOnBehalfByName", dataverse_type="string")
    createdonbehalfbyyominame            = Field("createdonbehalfbyyominame", str, schema_name="CreatedOnBehalfByYomiName", dataverse_type="string")
    creditlimit                          = Field("creditlimit", float, schema_name="CreditLimit", dataverse_type="decimal")
    creditlimit_base                     = Field("creditlimit_base", float, schema_name="CreditLimit_Base", dataverse_type="decimal")
    creditonhold                         = Field("creditonhold", bool, schema_name="CreditOnHold", dataverse_type="bool")
    customersizecode                     = Field("customersizecode", int, schema_name="CustomerSizeCode", dataverse_type="picklist")
    customertypecode                     = Field("customertypecode", int, schema_name="CustomerTypeCode", dataverse_type="picklist")
    defaultpricelevelid                  = Field("defaultpricelevelid", str, schema_name="DefaultPriceLevelId", dataverse_type="lookup")
    defaultpricelevelidname              = Field("defaultpricelevelidname", str, schema_name="DefaultPriceLevelIdName", dataverse_type="string")
    description                          = Field("description", str, schema_name="Description", dataverse_type="memo")
    donotbulkemail                       = Field("donotbulkemail", bool, schema_name="DoNotBulkEMail", dataverse_type="bool")
    donotbulkpostalmail                  = Field("donotbulkpostalmail", bool, schema_name="DoNotBulkPostalMail", dataverse_type="bool")
    donotemail                           = Field("donotemail", bool, schema_name="DoNotEMail", dataverse_type="bool")
    donotfax                             = Field("donotfax", bool, schema_name="DoNotFax", dataverse_type="bool")
    donotphone                           = Field("donotphone", bool, schema_name="DoNotPhone", dataverse_type="bool")
    donotpostalmail                      = Field("donotpostalmail", bool, schema_name="DoNotPostalMail", dataverse_type="bool")
    donotsendmm                          = Field("donotsendmm", bool, schema_name="DoNotSendMM", dataverse_type="bool")
    emailaddress1                        = Field("emailaddress1", str, schema_name="EMailAddress1", dataverse_type="string")
    emailaddress2                        = Field("emailaddress2", str, schema_name="EMailAddress2", dataverse_type="string")
    emailaddress3                        = Field("emailaddress3", str, schema_name="EMailAddress3", dataverse_type="string")
    entityimage_timestamp                = Field("entityimage_timestamp", int, schema_name="EntityImage_Timestamp", dataverse_type="int")
    entityimage_url                      = Field("entityimage_url", str, schema_name="EntityImage_URL", dataverse_type="string")
    entityimageid                        = Field("entityimageid", Any)  # unmapped type: ?
    exchangerate                         = Field("exchangerate", float, schema_name="ExchangeRate", dataverse_type="decimal")
    fax                                  = Field("fax", str, schema_name="Fax", dataverse_type="string")
    followemail                          = Field("followemail", bool, schema_name="FollowEmail", dataverse_type="bool")
    ftpsiteurl                           = Field("ftpsiteurl", str, schema_name="FtpSiteURL", dataverse_type="string")
    importsequencenumber                 = Field("importsequencenumber", int, schema_name="ImportSequenceNumber", dataverse_type="int")
    industrycode                         = Field("industrycode", int, schema_name="IndustryCode", dataverse_type="picklist")
    isprivate                            = Field("isprivate", bool, schema_name="IsPrivate", dataverse_type="bool")
    lastonholdtime                       = Field("lastonholdtime", str, schema_name="LastOnHoldTime", dataverse_type="datetime")
    lastusedincampaign                   = Field("lastusedincampaign", str, schema_name="LastUsedInCampaign", dataverse_type="datetime")
    marketcap                            = Field("marketcap", float, schema_name="MarketCap", dataverse_type="decimal")
    marketcap_base                       = Field("marketcap_base", float, schema_name="MarketCap_Base", dataverse_type="decimal")
    marketingonly                        = Field("marketingonly", bool, schema_name="MarketingOnly", dataverse_type="bool")
    masteraccountidname                  = Field("masteraccountidname", str, schema_name="MasterAccountIdName", dataverse_type="string")
    masteraccountidyominame              = Field("masteraccountidyominame", str, schema_name="MasterAccountIdYomiName", dataverse_type="string")
    masterid                             = Field("masterid", str, schema_name="MasterId", dataverse_type="lookup")
    merged                               = Field("merged", bool, schema_name="Merged", dataverse_type="bool")
    modifiedby                           = Field("modifiedby", str, schema_name="ModifiedBy", dataverse_type="lookup")
    modifiedbyexternalparty              = Field("modifiedbyexternalparty", str, schema_name="ModifiedByExternalParty", dataverse_type="lookup")
    modifiedbyexternalpartyname          = Field("modifiedbyexternalpartyname", str, schema_name="ModifiedByExternalPartyName", dataverse_type="string")
    modifiedbyexternalpartyyominame      = Field("modifiedbyexternalpartyyominame", str, schema_name="ModifiedByExternalPartyYomiName", dataverse_type="string")
    modifiedbyname                       = Field("modifiedbyname", str, schema_name="ModifiedByName", dataverse_type="string")
    modifiedbyyominame                   = Field("modifiedbyyominame", str, schema_name="ModifiedByYomiName", dataverse_type="string")
    modifiedon                           = Field("modifiedon", str, schema_name="ModifiedOn", dataverse_type="datetime")
    modifiedonbehalfby                   = Field("modifiedonbehalfby", str, schema_name="ModifiedOnBehalfBy", dataverse_type="lookup")
    modifiedonbehalfbyname               = Field("modifiedonbehalfbyname", str, schema_name="ModifiedOnBehalfByName", dataverse_type="string")
    modifiedonbehalfbyyominame           = Field("modifiedonbehalfbyyominame", str, schema_name="ModifiedOnBehalfByYomiName", dataverse_type="string")
    msa_managingpartnerid                = Field("msa_managingpartnerid", str, dataverse_type="lookup")
    msa_managingpartneridname            = Field("msa_managingpartneridname", str, schema_name="msa_managingpartneridName", dataverse_type="string")
    msa_managingpartneridyominame        = Field("msa_managingpartneridyominame", str, schema_name="msa_managingpartneridYomiName", dataverse_type="string")
    msdyn_accountkpiid                   = Field("msdyn_accountkpiid", str, dataverse_type="lookup")
    msdyn_accountkpiidname               = Field("msdyn_accountkpiidname", str, schema_name="msdyn_accountkpiidName", dataverse_type="string")
    msdyn_gdproptout                     = Field("msdyn_gdproptout", bool, dataverse_type="bool")
    msdyn_primarytimezone                = Field("msdyn_primarytimezone", int, schema_name="msdyn_PrimaryTimeZone", dataverse_type="int")
    msdyn_salesaccelerationinsightid     = Field("msdyn_salesaccelerationinsightid", str, dataverse_type="lookup")
    msdyn_salesaccelerationinsightidname = Field("msdyn_salesaccelerationinsightidname", str, schema_name="msdyn_salesaccelerationinsightidName", dataverse_type="string")
    msdyn_segmentid                      = Field("msdyn_segmentid", str, dataverse_type="lookup")
    msdyn_segmentidname                  = Field("msdyn_segmentidname", str, schema_name="msdyn_segmentidName", dataverse_type="string")
    name                                 = Field("name", str, schema_name="Name", dataverse_type="string")
    numberofemployees                    = Field("numberofemployees", int, schema_name="NumberOfEmployees", dataverse_type="int")
    onholdtime                           = Field("onholdtime", int, schema_name="OnHoldTime", dataverse_type="int")
    opendeals                            = Field("opendeals", int, schema_name="OpenDeals", dataverse_type="int")
    opendeals_date                       = Field("opendeals_date", str, schema_name="OpenDeals_Date", dataverse_type="datetime")
    opendeals_state                      = Field("opendeals_state", int, schema_name="OpenDeals_State", dataverse_type="int")
    openrevenue                          = Field("openrevenue", float, schema_name="OpenRevenue", dataverse_type="decimal")
    openrevenue_base                     = Field("openrevenue_base", float, schema_name="OpenRevenue_Base", dataverse_type="decimal")
    openrevenue_date                     = Field("openrevenue_date", str, schema_name="OpenRevenue_Date", dataverse_type="datetime")
    openrevenue_state                    = Field("openrevenue_state", int, schema_name="OpenRevenue_State", dataverse_type="int")
    originatingleadid                    = Field("originatingleadid", str, schema_name="OriginatingLeadId", dataverse_type="lookup")
    originatingleadidname                = Field("originatingleadidname", str, schema_name="OriginatingLeadIdName", dataverse_type="string")
    originatingleadidyominame            = Field("originatingleadidyominame", str, schema_name="OriginatingLeadIdYomiName", dataverse_type="string")
    overriddencreatedon                  = Field("overriddencreatedon", str, schema_name="OverriddenCreatedOn", dataverse_type="datetime")
    ownerid                              = Field("ownerid", str, schema_name="OwnerId", dataverse_type="lookup")
    owneridname                          = Field("owneridname", str, schema_name="OwnerIdName", dataverse_type="string")
    owneridtype                          = Field("owneridtype", str, schema_name="OwnerIdType")
    owneridyominame                      = Field("owneridyominame", str, schema_name="OwnerIdYomiName", dataverse_type="string")
    ownershipcode                        = Field("ownershipcode", int, schema_name="OwnershipCode", dataverse_type="picklist")
    owningbusinessunit                   = Field("owningbusinessunit", str, schema_name="OwningBusinessUnit", dataverse_type="lookup")
    owningbusinessunitname               = Field("owningbusinessunitname", str, schema_name="OwningBusinessUnitName", dataverse_type="string")
    owningteam                           = Field("owningteam", str, schema_name="OwningTeam", dataverse_type="lookup")
    owninguser                           = Field("owninguser", str, schema_name="OwningUser", dataverse_type="lookup")
    parentaccountid                      = Field("parentaccountid", str, schema_name="ParentAccountId", dataverse_type="lookup")
    parentaccountidname                  = Field("parentaccountidname", str, schema_name="ParentAccountIdName", dataverse_type="string")
    parentaccountidyominame              = Field("parentaccountidyominame", str, schema_name="ParentAccountIdYomiName", dataverse_type="string")
    participatesinworkflow               = Field("participatesinworkflow", bool, schema_name="ParticipatesInWorkflow", dataverse_type="bool")
    paymenttermscode                     = Field("paymenttermscode", int, schema_name="PaymentTermsCode", dataverse_type="picklist")
    preferredappointmentdaycode          = Field("preferredappointmentdaycode", int, schema_name="PreferredAppointmentDayCode", dataverse_type="picklist")
    preferredappointmenttimecode         = Field("preferredappointmenttimecode", int, schema_name="PreferredAppointmentTimeCode", dataverse_type="picklist")
    preferredcontactmethodcode           = Field("preferredcontactmethodcode", int, schema_name="PreferredContactMethodCode", dataverse_type="picklist")
    preferredequipmentid                 = Field("preferredequipmentid", str, schema_name="PreferredEquipmentId", dataverse_type="lookup")
    preferredequipmentidname             = Field("preferredequipmentidname", str, schema_name="PreferredEquipmentIdName", dataverse_type="string")
    preferredserviceid                   = Field("preferredserviceid", str, schema_name="PreferredServiceId", dataverse_type="lookup")
    preferredserviceidname               = Field("preferredserviceidname", str, schema_name="PreferredServiceIdName", dataverse_type="string")
    preferredsystemuserid                = Field("preferredsystemuserid", str, schema_name="PreferredSystemUserId", dataverse_type="lookup")
    preferredsystemuseridname            = Field("preferredsystemuseridname", str, schema_name="PreferredSystemUserIdName", dataverse_type="string")
    preferredsystemuseridyominame        = Field("preferredsystemuseridyominame", str, schema_name="PreferredSystemUserIdYomiName", dataverse_type="string")
    primarycontactid                     = Field("primarycontactid", str, schema_name="PrimaryContactId", dataverse_type="lookup")
    primarycontactidname                 = Field("primarycontactidname", str, schema_name="PrimaryContactIdName", dataverse_type="string")
    primarycontactidyominame             = Field("primarycontactidyominame", str, schema_name="PrimaryContactIdYomiName", dataverse_type="string")
    primarysatoriid                      = Field("primarysatoriid", str, schema_name="PrimarySatoriId", dataverse_type="string")
    primarytwitterid                     = Field("primarytwitterid", str, schema_name="PrimaryTwitterId", dataverse_type="string")
    processid                            = Field("processid", Any)  # unmapped type: ?
    revenue                              = Field("revenue", float, schema_name="Revenue", dataverse_type="decimal")
    revenue_base                         = Field("revenue_base", float, schema_name="Revenue_Base", dataverse_type="decimal")
    sharesoutstanding                    = Field("sharesoutstanding", int, schema_name="SharesOutstanding", dataverse_type="int")
    shippingmethodcode                   = Field("shippingmethodcode", int, schema_name="ShippingMethodCode", dataverse_type="picklist")
    sic                                  = Field("sic", str, schema_name="SIC", dataverse_type="string")
    slaid                                = Field("slaid", str, schema_name="SLAId", dataverse_type="lookup")
    slainvokedid                         = Field("slainvokedid", str, schema_name="SLAInvokedId", dataverse_type="lookup")
    slainvokedidname                     = Field("slainvokedidname", str, schema_name="SLAInvokedIdName", dataverse_type="string")
    slaname                              = Field("slaname", str, schema_name="SLAName", dataverse_type="string")
    stageid                              = Field("stageid", Any)  # unmapped type: ?
    statecode                            = Field("statecode", int, schema_name="StateCode", dataverse_type="picklist")
    statuscode                           = Field("statuscode", int, schema_name="StatusCode", dataverse_type="picklist")
    stockexchange                        = Field("stockexchange", str, schema_name="StockExchange", dataverse_type="string")
    teamsfollowed                        = Field("teamsfollowed", int, schema_name="TeamsFollowed", dataverse_type="int")
    telephone1                           = Field("telephone1", str, schema_name="Telephone1", dataverse_type="string")
    telephone2                           = Field("telephone2", str, schema_name="Telephone2", dataverse_type="string")
    telephone3                           = Field("telephone3", str, schema_name="Telephone3", dataverse_type="string")
    territorycode                        = Field("territorycode", int, schema_name="TerritoryCode", dataverse_type="picklist")
    territoryid                          = Field("territoryid", str, schema_name="TerritoryId", dataverse_type="lookup")
    territoryidname                      = Field("territoryidname", str, schema_name="TerritoryIdName", dataverse_type="string")
    tickersymbol                         = Field("tickersymbol", str, schema_name="TickerSymbol", dataverse_type="string")
    timespentbymeonemailandmeetings      = Field("timespentbymeonemailandmeetings", str, schema_name="TimeSpentByMeOnEmailAndMeetings", dataverse_type="string")
    timezoneruleversionnumber            = Field("timezoneruleversionnumber", int, schema_name="TimeZoneRuleVersionNumber", dataverse_type="int")
    transactioncurrencyid                = Field("transactioncurrencyid", str, schema_name="TransactionCurrencyId", dataverse_type="lookup")
    transactioncurrencyidname            = Field("transactioncurrencyidname", str, schema_name="TransactionCurrencyIdName", dataverse_type="string")
    traversedpath                        = Field("traversedpath", str, schema_name="TraversedPath", dataverse_type="string")
    utcconversiontimezonecode            = Field("utcconversiontimezonecode", int, schema_name="UTCConversionTimeZoneCode", dataverse_type="int")
    versionnumber                        = Field("versionnumber", int, schema_name="VersionNumber", dataverse_type="int")
    websiteurl                           = Field("websiteurl", str, schema_name="WebSiteURL", dataverse_type="string")
    yominame                             = Field("yominame", str, schema_name="YomiName", dataverse_type="string")

    # --- Navigation properties (expand) ---
    # createdby_nav = NavField("createdby")  # uncomment + set nav-property name to enable .expand()
    # createdbyexternalparty_nav = NavField("createdbyexternalparty")  # uncomment + set nav-property name to enable .expand()
    # createdonbehalfby_nav = NavField("createdonbehalfby")  # uncomment + set nav-property name to enable .expand()
    # defaultpricelevelid_nav = NavField("defaultpricelevel")  # uncomment + set nav-property name to enable .expand()
    # masterid_nav = NavField("master")  # uncomment + set nav-property name to enable .expand()
    # modifiedby_nav = NavField("modifiedby")  # uncomment + set nav-property name to enable .expand()
    # modifiedbyexternalparty_nav = NavField("modifiedbyexternalparty")  # uncomment + set nav-property name to enable .expand()
    # modifiedonbehalfby_nav = NavField("modifiedonbehalfby")  # uncomment + set nav-property name to enable .expand()
    # msa_managingpartnerid_nav = NavField("msa_managingpartner")  # uncomment + set nav-property name to enable .expand()
    # msdyn_accountkpiid_nav = NavField("msdyn_accountkpi")  # uncomment + set nav-property name to enable .expand()
    # msdyn_salesaccelerationinsightid_nav = NavField("msdyn_salesaccelerationinsight")  # uncomment + set nav-property name to enable .expand()
    # msdyn_segmentid_nav = NavField("msdyn_segment")  # uncomment + set nav-property name to enable .expand()
    # originatingleadid_nav = NavField("originatinglead")  # uncomment + set nav-property name to enable .expand()
    # ownerid_nav = NavField("owner")  # uncomment + set nav-property name to enable .expand()
    # owningbusinessunit_nav = NavField("owningbusinessunit")  # uncomment + set nav-property name to enable .expand()
    # owningteam_nav = NavField("owningteam")  # uncomment + set nav-property name to enable .expand()
    # owninguser_nav = NavField("owninguser")  # uncomment + set nav-property name to enable .expand()
    # parentaccountid_nav = NavField("parentaccount")  # uncomment + set nav-property name to enable .expand()
    # preferredequipmentid_nav = NavField("preferredequipment")  # uncomment + set nav-property name to enable .expand()
    # preferredserviceid_nav = NavField("preferredservice")  # uncomment + set nav-property name to enable .expand()
    # preferredsystemuserid_nav = NavField("preferredsystemuser")  # uncomment + set nav-property name to enable .expand()
    # primarycontactid_nav = NavField("primarycontact")  # uncomment + set nav-property name to enable .expand()
    # slaid_nav = NavField("sla")  # uncomment + set nav-property name to enable .expand()
    # slainvokedid_nav = NavField("slainvoked")  # uncomment + set nav-property name to enable .expand()
    # territoryid_nav = NavField("territory")  # uncomment + set nav-property name to enable .expand()
    # transactioncurrencyid_nav = NavField("transactioncurrency")  # uncomment + set nav-property name to enable .expand()
