# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
Walkthrough demonstrating the strongly-typed entity model in the Dataverse SDK.

This example shows the same operations as walkthrough.py but using typed
entity classes instead of plain string-keyed dictionaries:

- Defining Entity subclasses with typed field descriptors
- Typed picklist and boolean option sets
- Single and multiple record CRUD with typed instances
- Querying with descriptor-based filter expressions
- Payload helpers (to_create_payload / to_update_payload)
- Entity introspection with fields()
- QueryBuilder with typed results

Prerequisites:
- pip install PowerPlatform-Dataverse-Client
- pip install azure-identity
- The table new_WalkthroughTypedDemo must either be created on first run
  (the walkthrough creates it) or already exist with matching columns.
"""

import sys
import time
from azure.identity import InteractiveBrowserCredential

from PowerPlatform.Dataverse.client import DataverseClient
from PowerPlatform.Dataverse.core.errors import MetadataError
from PowerPlatform.Dataverse.models.entity import Entity
from PowerPlatform.Dataverse.models.datatypes import Guid, Text, Memo, Integer, DecimalNumber
from PowerPlatform.Dataverse.models.picklist import PicklistBase, PicklistOption
from PowerPlatform.Dataverse.models.boolean import BooleanBase, BooleanOption


# ============================================================================
# TYPED ENTITY DEFINITIONS
# ============================================================================
# These would normally live in their own module (e.g. generated by the SDK
# code generator or written by hand to match your Dataverse table schema).

class WalkthroughPriority(PicklistBase):
    """Strongly-typed option set for the new_priority column."""
    Low    = PicklistOption(1, "Low")
    Medium = PicklistOption(2, "Medium")
    High   = PicklistOption(3, "High")


class WalkthroughCompleted(BooleanBase):
    """Strongly-typed two-option set for the new_completed column."""
    Yes = BooleanOption(True,  "Completed")
    No  = BooleanOption(False, "Not Completed")


class WalkthroughDemo(
    Entity,
    table="new_walkthroughtypeddemo",
    primary_key="new_walkthroughtypeddemoid",
    entity_set="new_walkthroughtypeeddemos",
):
    """Typed entity class matching the new_WalkthroughTypedDemo Dataverse table."""

    new_walkthroughtypeddemoid = Guid(writable_on_create=False, writable_on_update=False)
    new_title                  = Text(nullable=False, max_length=200)
    new_quantity               = Integer()
    new_amount                 = DecimalNumber()
    new_completed              = WalkthroughCompleted()
    new_notes                  = Memo()
    new_priority               = WalkthroughPriority()


# ============================================================================
# Helpers
# ============================================================================

def log_call(description):
    print(f"\n-> {description}")


def backoff(op, *, delays=(0, 2, 5, 10, 20, 20)):
    last = None
    total_delay = 0
    attempts = 0
    for d in delays:
        if d:
            time.sleep(d)
            total_delay += d
        attempts += 1
        try:
            result = op()
            if attempts > 1:
                print(f"   [INFO] Backoff succeeded after {attempts - 1} retry(s); waited {total_delay}s total.")
            return result
        except Exception as ex:  # noqa: BLE001
            last = ex
            continue
    if last:
        print(f"   [WARN] Backoff exhausted after {max(attempts - 1, 0)} retry(s); waited {total_delay}s total.")
        raise last


def main():
    print("=" * 80)
    print("Dataverse SDK — Typed Entity Walkthrough")
    print("=" * 80)

    # ============================================================================
    # 1. SETUP & AUTHENTICATION
    # ============================================================================
    print("\n" + "=" * 80)
    print("1. Setup & Authentication")
    print("=" * 80)

    base_url = input("Enter Dataverse org URL (e.g. https://yourorg.crm.dynamics.com): ").strip()
    if not base_url:
        print("No URL entered; exiting.")
        sys.exit(1)

    base_url = base_url.rstrip("/")

    log_call("InteractiveBrowserCredential()")
    credential = InteractiveBrowserCredential()

    log_call(f"DataverseClient(base_url='{base_url}', credential=...)")
    with DataverseClient(base_url=base_url, credential=credential) as client:
        print(f"[OK] Connected to: {base_url}")
        _run_walkthrough(client)


def _run_walkthrough(client):
    table_name = "new_WalkthroughTypedDemo"

    # ============================================================================
    # 2. ENTITY CLASS OVERVIEW
    # ============================================================================
    print("\n" + "=" * 80)
    print("2. Entity Class Overview")
    print("=" * 80)

    print("WalkthroughDemo entity metadata:")
    print(f"  Table (logical name) : {WalkthroughDemo._logical_name}")
    print(f"  Primary key          : {WalkthroughDemo._primary_id}")

    print("\nField descriptors (via WalkthroughDemo.fields()):")
    for attr_name, descriptor in WalkthroughDemo.fields().items():
        wc = "rw" if getattr(descriptor, "writable_on_create", True) else "r-"
        wu = "rw" if getattr(descriptor, "writable_on_update", True) else "r-"
        print(f"  {attr_name:<35} {type(descriptor).__name__:<20} create={wc}  update={wu}")

    print("\nWalkthroughPriority options:")
    for name, opt in WalkthroughPriority.options().items():
        print(f"  {name:<12} = {int(opt)}  ({opt.label!r})")

    # ============================================================================
    # 3. TABLE CREATION (METADATA)
    # ============================================================================
    print("\n" + "=" * 80)
    print("3. Table Creation (Metadata)")
    print("=" * 80)

    log_call(f"client.tables.get('{table_name}')")
    table_info = backoff(lambda: client.tables.get(table_name))

    if table_info:
        print(f"[OK] Table already exists: {table_info.get('table_schema_name')}")
    else:
        log_call("client.tables.create(WalkthroughDemo)  # columns derived from field descriptors")
        table_info = backoff(lambda: client.tables.create(WalkthroughDemo))
        print(f"[OK] Created table: {table_info.get('table_schema_name')}")
        print(f"  Columns created: {', '.join(table_info.get('columns_created', []))}")

    # ============================================================================
    # 4. CREATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("4. Create Operations")
    print("=" * 80)

    # Build a typed entity instance and persist it
    log_call("WalkthroughDemo(name=...) + client.records.create(WalkthroughDemo, entity)")
    task1 = WalkthroughDemo(
        new_title="Complete project documentation",
        new_quantity=5,
        new_amount=1250.50,
        new_completed=False,
        new_notes="This is a multiline memo field.\nIt supports longer text content.",
        new_priority=WalkthroughPriority.Medium,
    )
    print(f"  Entity before create: {task1!r}")
    print(f"  to_create_payload().as_dict(): {task1.to_create_payload().as_dict()}")

    id1 = backoff(lambda: client.records.create(WalkthroughDemo, task1))
    print(f"[OK] Created single record: {id1}")

    # Multiple create — list of typed entity instances
    log_call("client.records.create(WalkthroughDemo, [entity1, entity2, entity3])")
    tasks = [
        WalkthroughDemo(
            new_title="Review code changes",
            new_quantity=10,
            new_amount=500.00,
            new_completed=True,
            new_priority=WalkthroughPriority.High,
        ),
        WalkthroughDemo(
            new_title="Update test cases",
            new_quantity=8,
            new_amount=750.25,
            new_completed=False,
            new_priority=WalkthroughPriority.Low,
        ),
        WalkthroughDemo(
            new_title="Deploy to staging",
            new_quantity=3,
            new_amount=2000.00,
            new_completed=False,
            new_priority=WalkthroughPriority.High,
        ),
    ]
    ids = backoff(lambda: client.records.create(WalkthroughDemo, tasks))
    print(f"[OK] Created {len(ids)} records: {ids}")

    # ============================================================================
    # 5. READ OPERATIONS — TYPED RESULTS
    # ============================================================================
    print("\n" + "=" * 80)
    print("5. Read Operations — Typed Results")
    print("=" * 80)

    # Single read by ID — returns WalkthroughDemo instance
    log_call(f"client.records.get(WalkthroughDemo, '{id1}')")
    record: WalkthroughDemo = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    print("[OK] Retrieved single record as typed instance:")
    print(f"  type(record)       = {type(record).__name__}")
    print(f"  record.new_title   = {record.new_title!r}")
    print(f"  record.new_quantity= {record.new_quantity}")
    print(f"  record.new_amount  = {record.new_amount}")
    print(f"  record.new_notes   = {record.new_notes!r}")
    priority_opt = WalkthroughPriority.from_value(record.new_priority)
    print(f"  record.new_priority= {record.new_priority}  ({priority_opt.label if priority_opt else 'unknown'})")

    # Multiple read with filter — yields pages of WalkthroughDemo
    log_call("client.records.get(WalkthroughDemo, filter='new_quantity gt 5')")
    all_records = []
    for page in backoff(lambda: client.records.get(
        WalkthroughDemo, filter="new_quantity gt 5"
    )):
        all_records.extend(page)
    print(f"[OK] Found {len(all_records)} records with new_quantity > 5:")
    for rec in all_records:
        print(f"  - {rec.new_title!r}  qty={rec.new_quantity}")

    # ============================================================================
    # 6. UPDATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("6. Update Operations")
    print("=" * 80)

    # Build a patch entity — only set the fields to change
    log_call("patch = WalkthroughDemo(...) + client.records.update(WalkthroughDemo, id1, patch)")
    patch = WalkthroughDemo(
        new_quantity=100,
        new_notes="Updated memo field.\nNow with revised content.",
    )
    print(f"  to_update_payload().as_dict(): {patch.to_update_payload().as_dict()}")
    backoff(lambda: client.records.update(WalkthroughDemo, id1, patch))
    updated: WalkthroughDemo = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    print(f"[OK] Updated record: new_quantity={updated.new_quantity}, new_notes={updated.new_notes!r}")

    # Broadcast the same dict patch to multiple records
    log_call(f"client.records.update(WalkthroughDemo, {ids}, {{'new_completed': True}})")
    backoff(lambda: client.records.update(WalkthroughDemo, ids, {"new_completed": True}))
    print(f"[OK] Updated {len(ids)} records to new_completed=True")

    # ============================================================================
    # 7. PAGING DEMO
    # ============================================================================
    print("\n" + "=" * 80)
    print("7. Paging Demo")
    print("=" * 80)

    log_call("client.records.create(WalkthroughDemo, [20 typed entities])")
    paging_tasks = [
        WalkthroughDemo(
            new_title=f"Paging item {i}",
            new_quantity=i,
            new_amount=float(i * 10),
            new_completed=False,
            new_priority=WalkthroughPriority.Low,
        )
        for i in range(1, 21)
    ]
    paging_ids = backoff(lambda: client.records.create(WalkthroughDemo, paging_tasks))
    print(f"[OK] Created {len(paging_ids)} records for paging demo")

    log_call("client.records.get(WalkthroughDemo, orderby=[...], page_size=5)")
    for page_num, page in enumerate(
        backoff(lambda: client.records.get(
            WalkthroughDemo,
            orderby=["new_quantity"],
            page_size=5,
        )),
        start=1,
    ):
        titles = [r.new_title for r in page]
        print(f"  Page {page_num}: {len(page)} records — {titles}")

    # ============================================================================
    # 8. QUERYBUILDER WITH DESCRIPTOR FILTERS
    # ============================================================================
    print("\n" + "=" * 80)
    print("8. QueryBuilder with Descriptor Filters")
    print("=" * 80)

    # Pass the entity class to builder() — results come back as typed instances
    log_call("client.query.builder(WalkthroughDemo).select(descriptors).where(descriptor expr).execute()")
    print("Descriptor-based select and filter:")
    results = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount, WalkthroughDemo.new_priority)
            .where(WalkthroughDemo.new_completed == False)
            .order_by(WalkthroughDemo.new_amount, descending=True)
            .top(5)
            .execute()
        )
    )
    print(f"[OK] {len(results)} incomplete records (by descriptor filter):")
    for rec in results:
        opt = WalkthroughPriority.from_value(rec.new_priority)
        label = opt.label if opt else "?"
        print(f"  - {rec.new_title!r}  amount={rec.new_amount}  priority={label}")

    # Combine descriptor filter with fluent filter helpers
    log_call("builder.where(descriptor expr) + .filter_gt(str, value)")
    combined = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
            .where(WalkthroughDemo.new_completed == False)
            .filter_gt("new_quantity", 5)
            .order_by("new_quantity")
            .execute()
        )
    )
    print(f"[OK] {len(combined)} incomplete records with new_quantity > 5:")
    for rec in combined[:5]:
        print(f"  - {rec.new_title!r}  qty={rec.new_quantity}")

    # filter_in with typed picklist options
    log_call("builder.filter_in(WalkthroughDemo.new_priority, [High, Low])")
    priority_results = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_priority)
            .filter_in("new_priority", [WalkthroughPriority.High, WalkthroughPriority.Low])
            .execute()
        )
    )
    print(f"[OK] {len(priority_results)} records with High or Low priority")
    for rec in priority_results[:5]:
        opt = WalkthroughPriority.from_value(rec.new_priority)
        print(f"  - {rec.new_title!r}  priority={opt.label if opt else '?'}")

    # ============================================================================
    # 9. PAYLOAD HELPERS
    # ============================================================================
    print("\n" + "=" * 80)
    print("9. Payload Helpers")
    print("=" * 80)

    print("to_create_payload() strips fields with writable_on_create=False (e.g. primary key):")
    full = WalkthroughDemo(
        new_walkthroughtypeddemoid="some-guid",
        new_title="Demo record",
        new_quantity=42,
    )
    create_payload = full.to_create_payload()
    update_payload = full.to_update_payload()
    print(f"  full.as_dict()                  = {full.as_dict()}")
    print(f"  to_create_payload().as_dict()   = {create_payload.as_dict()}")
    print(f"  to_update_payload().as_dict()   = {update_payload.as_dict()}")
    assert "new_walkthroughtypeddemoid" not in create_payload.as_dict(), "PK must be excluded from create"
    assert "new_walkthroughtypeddemoid" not in update_payload.as_dict(), "PK must be excluded from update"
    print("[OK] Primary key correctly excluded from both payloads")

    print("\nfrom_dict() hydrates a typed instance from a plain dict (e.g. an OData response):")
    raw = {"new_title": "From OData", "new_quantity": 7, "new_priority": 3}
    hydrated = WalkthroughDemo.from_dict(raw)
    print(f"  type(hydrated)         = {type(hydrated).__name__}")
    print(f"  hydrated.new_title     = {hydrated.new_title!r}")
    print(f"  hydrated.new_quantity  = {hydrated.new_quantity}")
    opt = WalkthroughPriority.from_value(hydrated.new_priority)
    print(f"  hydrated.new_priority  = {hydrated.new_priority}  ({opt.label if opt else '?'})")
    print("[OK] Typed instance hydrated from dict")

    # ============================================================================
    # 10. DELETE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("10. Delete Operations")
    print("=" * 80)

    log_call(f"client.records.delete(WalkthroughDemo, '{id1}')")
    backoff(lambda: client.records.delete(WalkthroughDemo, id1))
    print(f"[OK] Deleted single record: {id1}")

    all_remaining = ids + paging_ids
    log_call(f"client.records.delete(WalkthroughDemo, [{len(all_remaining)} IDs])")
    job_id = backoff(lambda: client.records.delete(WalkthroughDemo, all_remaining))
    print(f"[OK] Bulk delete job started: {job_id}  ({len(all_remaining)} records)")

    # ============================================================================
    # 11. CLEANUP
    # ============================================================================
    print("\n" + "=" * 80)
    print("11. Cleanup")
    print("=" * 80)

    log_call(f"client.tables.delete('{table_name}')")
    try:
        backoff(lambda: client.tables.delete(table_name))
        print(f"[OK] Deleted table: {table_name}")
    except MetadataError as ex:
        if "not found" in str(ex).lower():
            print(f"[OK] Table already removed: {table_name}")
        else:
            raise

    # ============================================================================
    # SUMMARY
    # ============================================================================
    print("\n" + "=" * 80)
    print("Typed Entity Walkthrough Complete!")
    print("=" * 80)
    print("\nDemonstrated operations:")
    print("  [OK] Defining Entity subclasses with typed field descriptors")
    print("  [OK] PicklistBase / PicklistOption for typed option sets")
    print("  [OK] BooleanBase / BooleanOption for typed two-option columns")
    print("  [OK] Entity.fields() for schema introspection")
    print("  [OK] Typed single and multiple record creation")
    print("  [OK] Typed single and multiple record reads")
    print("  [OK] Typed record updates (entity patch + dict patch)")
    print("  [OK] Paging with typed results")
    print("  [OK] QueryBuilder with descriptor-based filter expressions")
    print("  [OK] to_create_payload() / to_update_payload() stripping read-only fields")
    print("  [OK] from_dict() hydrating typed instances from OData responses")
    print("  [OK] Single and bulk delete with typed table reference")
    print("  [OK] Table cleanup")
    print("=" * 80)


if __name__ == "__main__":
    main()
