# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
Walkthrough demonstrating core Dataverse SDK operations using strongly typed entities.

This is the typed counterpart to walkthrough.py.  Every section performs the
same operations as the original — the only difference is how those operations
are expressed:

  String-based (original)           Typed (this file)
  ─────────────────────────────     ──────────────────────────────────────────
  builder("new_WalkthroughDemo")    builder(WalkthroughDemo)
  .select("new_Title", ...)         .select(WalkthroughDemo.new_title, ...)
  .filter_eq("new_Completed", 0)    .where(WalkthroughDemo.new_completed == False)
  record.get("new_title")           demo.new_title
  {"new_Title": "x", ...}           WalkthroughDemo(new_title="x", ...)

Under the hood both paths compile to identical OData requests.  No changes
were made to the HTTP layer, auth, or data layer.

This example shows:
- Defining a typed entity class that mirrors a Dataverse table
- Single and multiple record CRUD using WalkthroughDemo(...)
- Typed attribute access on query results (demo.new_title vs record.get())
- Querying with typed field expressions (WalkthroughDemo.statecode == 0)
- Composable typed filter conditions (&, |, ~)
- Paging, to_dataframe(), expand, SQL, batch — all still work unchanged

Prerequisites:
- pip install PowerPlatform-Dataverse-Client
- pip install azure-identity
"""

import sys
import json
import time
from enum import IntEnum
from azure.identity import InteractiveBrowserCredential
from PowerPlatform.Dataverse.client import DataverseClient
from PowerPlatform.Dataverse.core.errors import MetadataError
from PowerPlatform.Dataverse.models.entity import Entity
from PowerPlatform.Dataverse.models.query_builder import ExpandOption
import requests


# Simple logging helper
def log_call(description):
    print(f"\n-> {description}")


# Define enum for priority picklist
class Priority(IntEnum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3


# ---------------------------------------------------------------------------
# Typed entity classes
#
# These mirror the Dataverse tables used in this walkthrough.
# In a real project these would be auto-generated by the generate() tool.
# Field names are the OData logical names (lowercase).
# ---------------------------------------------------------------------------

class WalkthroughDemo(Entity, table="new_WalkthroughDemo", primary_key="new_walkthroughdemoid"):
    """Typed entity for the new_WalkthroughDemo custom table."""
    new_walkthroughdemoid: str
    new_title:             str
    new_quantity:          int
    new_amount:            float
    new_completed:         bool
    new_notes:             str
    new_priority:          int


class Account(Entity, table="account", primary_key="accountid"):
    """Typed entity for the built-in account table (used in expand demo)."""
    accountid:        str
    name:             str
    # When .expand("primarycontactid") is used, this holds the nested contact
    # dict rather than the lookup ID string.
    primarycontactid: str
    # Navigation collection — populated when .expand("Account_Tasks") is used.
    Account_Tasks:    list


def backoff(op, *, delays=(0, 2, 5, 10, 20, 20)):
    last = None
    total_delay = 0
    attempts = 0
    for d in delays:
        if d:
            time.sleep(d)
            total_delay += d
        attempts += 1
        try:
            result = op()
            if attempts > 1:
                retry_count = attempts - 1
                print(f"   [INFO] Backoff succeeded after {retry_count} retry(s); waited {total_delay}s total.")
            return result
        except Exception as ex:  # noqa: BLE001
            last = ex
            continue
    if last:
        if attempts:
            retry_count = max(attempts - 1, 0)
            print(f"   [WARN] Backoff exhausted after {retry_count} retry(s); waited {total_delay}s total.")
        raise last


def main():
    print("=" * 80)
    print("Dataverse SDK Walkthrough — Strongly Typed")
    print("=" * 80)

    # ============================================================================
    # 1. SETUP & AUTHENTICATION
    # ============================================================================
    print("\n" + "=" * 80)
    print("1. Setup & Authentication")
    print("=" * 80)

    base_url = input("Enter Dataverse org URL (e.g. https://yourorg.crm.dynamics.com): ").strip()
    if not base_url:
        print("No URL entered; exiting.")
        sys.exit(1)

    base_url = base_url.rstrip("/")

    log_call("InteractiveBrowserCredential()")
    credential = InteractiveBrowserCredential()

    log_call(f"DataverseClient(base_url='{base_url}', credential=...)")
    with DataverseClient(base_url=base_url, credential=credential) as client:
        print(f"[OK] Connected to: {base_url}")
        _run_walkthrough(client)


def _run_walkthrough(client):
    # ============================================================================
    # 2. TABLE CREATION (METADATA)
    # ============================================================================
    print("\n" + "=" * 80)
    print("2. Table Creation (Metadata)")
    print("=" * 80)

    # Pass the entity class directly — the SDK resolves WalkthroughDemo.__table__
    # internally, so there's no need to reference the string name at all.
    log_call("client.tables.get(WalkthroughDemo)")
    table_info = backoff(lambda: client.tables.get(WalkthroughDemo))

    if table_info:
        print(f"[OK] Table already exists: {table_info.get('table_schema_name')}")
        print(f"  Logical Name: {table_info.get('table_logical_name')}")
        print(f"  Entity Set: {table_info.get('entity_set_name')}")
    else:
        log_call("client.tables.create(WalkthroughDemo, columns={...})")
        columns = {
            "new_Title": "string",
            "new_Quantity": "int",
            "new_Amount": "decimal",
            "new_Completed": "bool",
            "new_Notes": "memo",
            "new_Priority": Priority,
        }
        table_info = backoff(lambda: client.tables.create(WalkthroughDemo, columns))
        print(f"[OK] Created table: {table_info.get('table_schema_name')}")
        print(f"  Columns created: {', '.join(table_info.get('columns_created', []))}")

    # ============================================================================
    # 3. CREATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("3. Create Operations")
    print("=" * 80)

    # Pass a WalkthroughDemo instance — table is inferred, field names validated.
    log_call("client.records.create(WalkthroughDemo(...))")
    id1 = backoff(lambda: client.records.create(
        WalkthroughDemo(
            new_title="Complete project documentation",
            new_quantity=5,
            new_amount=1250.50,
            new_completed=False,
            new_notes="This is a multiline memo field.\nIt supports longer text content.",
            new_priority=Priority.MEDIUM,
        )
    ))
    print(f"[OK] Created single record: {id1}")

    log_call("client.records.create([WalkthroughDemo(...), ...])")
    ids = backoff(lambda: client.records.create(
        [
            WalkthroughDemo(
                new_title="Review code changes",
                new_quantity=10,
                new_amount=500.00,
                new_completed=True,
                new_priority=Priority.HIGH,
            ),
            WalkthroughDemo(
                new_title="Update test cases",
                new_quantity=8,
                new_amount=750.25,
                new_completed=False,
                new_priority=Priority.LOW,
            ),
            WalkthroughDemo(
                new_title="Deploy to staging",
                new_quantity=3,
                new_amount=2000.00,
                new_completed=False,
                new_priority=Priority.HIGH,
            ),
        ]
    ))
    print(f"[OK] Created {len(ids)} records: {ids}")

    # ============================================================================
    # 4. READ OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("4. Read Operations")
    print("=" * 80)

    # Single read by ID — client.records.get() returns a Record.
    # WalkthroughDemo.from_record() hydrates it into a typed instance.
    log_call(f"client.records.get(WalkthroughDemo, id1)  →  WalkthroughDemo.from_record(record)")
    record = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    demo = WalkthroughDemo.from_record(record)
    print("[OK] Retrieved single record (typed attribute access):")
    print(
        json.dumps(
            {
                "new_walkthroughdemoid": demo.new_walkthroughdemoid,
                "new_title":            demo.new_title,
                "new_quantity":         demo.new_quantity,
                "new_amount":           demo.new_amount,
                "new_completed":        demo.new_completed,
                "new_notes":            demo.new_notes,
                "new_priority":         demo.new_priority,
                # Formatted annotation still accessed via dict key (OData annotation)
                "new_priority@FormattedValue": record.get(
                    "new_priority@OData.Community.Display.V1.FormattedValue"
                ),
            },
            indent=2,
        )
    )

    # Multiple read with typed filter expression.
    # WalkthroughDemo.new_quantity > 5  produces FilterExpression("new_quantity gt 5")
    log_call("client.query.builder(WalkthroughDemo).where(WalkthroughDemo.new_quantity > 5).execute()")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
            .where(WalkthroughDemo.new_quantity > 5)
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with new_quantity > 5")
    for d in demos:
        print(f"  - new_title='{d.new_title}', new_quantity={d.new_quantity}")

    # ============================================================================
    # 5. UPDATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("5. Update Operations")
    print("=" * 80)

    log_call("client.records.update(WalkthroughDemo, id1, WalkthroughDemo(...))")
    backoff(lambda: client.records.update(
        WalkthroughDemo,
        id1,
        WalkthroughDemo(
            new_quantity=100,
            new_notes="Updated memo field.\nNow with revised content across multiple lines.",
        ),
    ))
    updated_record = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    updated = WalkthroughDemo.from_record(updated_record)
    print(f"[OK] Updated single record new_quantity: {updated.new_quantity}")
    print(f"  new_notes: {repr(updated.new_notes)}")

    # Broadcast same change to all ids
    log_call(f"client.records.update(WalkthroughDemo, [{len(ids)} IDs], WalkthroughDemo(...))")
    backoff(lambda: client.records.update(WalkthroughDemo, ids, WalkthroughDemo(new_completed=True)))
    print(f"[OK] Updated {len(ids)} records to new_completed=True")

    # ============================================================================
    # 6. PAGING DEMO
    # ============================================================================
    print("\n" + "=" * 80)
    print("6. Paging Demo")
    print("=" * 80)

    log_call("client.records.create([20 × WalkthroughDemo(...)])")
    paging_records = [
        WalkthroughDemo(
            new_title=f"Paging test item {i}",
            new_quantity=i,
            new_amount=i * 10.0,
            new_completed=False,
            new_priority=Priority.LOW,
        )
        for i in range(1, 21)
    ]
    paging_ids = backoff(lambda: client.records.create(paging_records))
    print(f"[OK] Created {len(paging_ids)} records for paging demo")

    # Typed builder with page_size — results are WalkthroughDemo instances
    log_call("client.query.builder(WalkthroughDemo).order_by(WalkthroughDemo.new_quantity).page_size(5).execute(by_page=True)")
    print("Fetching records with page_size=5...")
    for page_num, page in enumerate(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_walkthroughdemoid, WalkthroughDemo.new_quantity)
            .order_by(WalkthroughDemo.new_quantity)
            .page_size(5)
            .execute(by_page=True)
        ),
        start=1,
    ):
        record_ids = [d.new_walkthroughdemoid[:8] + "..." for d in page]
        print(f"  Page {page_num}: {len(page)} records - IDs: {record_ids}")

    # ============================================================================
    # 7. QUERYBUILDER — TYPED FLUENT QUERIES
    # ============================================================================
    print("\n" + "=" * 80)
    print("7. QueryBuilder — Typed Fluent Queries")
    print("=" * 80)

    # Basic typed query: field descriptors in select, typed condition in where
    log_call("client.query.builder(WalkthroughDemo).select(fields).where(expr).order_by(field).execute()")
    print("Querying incomplete records ordered by amount (typed builder)...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount, WalkthroughDemo.new_priority)
            .where(WalkthroughDemo.new_completed == False)
            .order_by(WalkthroughDemo.new_amount, descending=True)
            .top(10)
            .execute()
        )
    )
    print(f"[OK] Typed query found {len(demos)} incomplete records:")
    for d in demos[:5]:
        print(f"  - '{d.new_title}' amount={d.new_amount}")

    # in_() method on a FieldDescriptor
    log_call("WalkthroughDemo.new_priority.in_([Priority.HIGH, Priority.LOW])")
    print("Querying records with HIGH or LOW priority (typed in_())...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_priority)
            .where(WalkthroughDemo.new_priority.in_([Priority.HIGH, Priority.LOW]))
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with HIGH or LOW priority")
    for d in demos[:5]:
        print(f"  - '{d.new_title}' priority={d.new_priority}")

    # between() method on a FieldDescriptor
    log_call("WalkthroughDemo.new_amount.between(500, 1500)")
    print("Querying records with amount between 500 and 1500 (typed between())...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount)
            .where(WalkthroughDemo.new_amount.between(500, 1500))
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with amount in [500, 1500]")
    for d in demos:
        print(f"  - '{d.new_title}' amount={d.new_amount}")

    # & operator composes two typed conditions into a single AND expression
    log_call("(WalkthroughDemo.new_completed == False) & (WalkthroughDemo.new_amount > 100)")
    print("Querying with typed AND expression...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount, WalkthroughDemo.new_quantity)
            .where(
                (WalkthroughDemo.new_completed == False)
                & (WalkthroughDemo.new_amount > 100)
            )
            .order_by(WalkthroughDemo.new_amount, descending=True)
            .top(5)
            .execute()
        )
    )
    print(f"[OK] AND expression found {len(demos)} records:")
    for d in demos:
        print(f"  - '{d.new_title}' amount={d.new_amount} qty={d.new_quantity}")

    # Multiple where() calls AND-joined + between() + paged (by_page=True)
    log_call("Multiple .where() calls + .between() + paging")
    print("Querying with combined typed filters and paging...")
    combined_page_count = 0
    combined_record_count = 0
    for page in backoff(
        lambda: client.query.builder(WalkthroughDemo)
        .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
        .where(WalkthroughDemo.new_completed == False)
        .where(WalkthroughDemo.new_quantity.between(1, 15))
        .order_by(WalkthroughDemo.new_quantity)
        .page_size(3)
        .execute(by_page=True)
    ):
        combined_page_count += 1
        combined_record_count += len(page)
        titles = [d.new_title for d in page]
        print(f"  Page {combined_page_count}: {len(page)} records - {titles}")
    print(f"[OK] Combined query: {combined_record_count} records across {combined_page_count} page(s)")

    # to_dataframe() — returns a pandas DataFrame (inherently untyped, unchanged)
    log_call("client.query.builder(WalkthroughDemo).where(...).to_dataframe()")
    print("Querying completed records as a pandas DataFrame (to_dataframe)...")
    df = backoff(
        lambda: client.query.builder(WalkthroughDemo)
        .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
        .where(WalkthroughDemo.new_completed == True)
        .to_dataframe()
    )
    print(f"[OK] to_dataframe() returned {len(df)} rows, columns: {list(df.columns)}")
    if not df.empty:
        print(f"  First row: new_title='{df.iloc[0].get('new_title')}', new_quantity={df.iloc[0].get('new_quantity')}")
        print(f"  Sum of new_quantity: {df['new_quantity'].sum()}")
    else:
        print("  (empty DataFrame)")

    # ============================================================================
    # 8. EXPAND (NAVIGATION PROPERTIES)
    # ============================================================================
    print("\n" + "=" * 80)
    print("8. Expand (Navigation Properties)")
    print("=" * 80)

    # Typed builder for account; navigation property expand is still string-based
    log_call("client.query.builder(Account).select(Account.name).expand('primarycontactid').top(3).execute()")
    print("Querying accounts with primary contact expanded...")
    try:
        accounts = list(
            backoff(
                lambda: client.query.builder(Account)
                .select(Account.name)
                .expand("primarycontactid")
                .top(3)
                .execute()
            )
        )
        print(f"[OK] Found {len(accounts)} accounts with expanded contact:")
        for acc in accounts:
            # When expanded, primarycontactid holds the nested contact dict.
            contact = acc.primarycontactid
            contact_name = contact.get("fullname", "(none)") if contact else "(no contact)"
            print(f"  - '{acc.name}' -> Contact: {contact_name}")
    except Exception as e:  # noqa: BLE001
        print(f"[SKIP] Expand demo skipped (no accounts in org): {e}")

    # ExpandOption with nested $select, $filter, $orderby, $top
    log_call("ExpandOption('Account_Tasks').select('subject').order_by('createdon', descending=True).top(3)")
    print("Querying accounts with nested expand options on tasks...")
    try:
        tasks_opt = (
            ExpandOption("Account_Tasks")
            .select("subject", "createdon")
            .order_by("createdon", descending=True)
            .top(3)
        )
        accounts = list(
            backoff(
                lambda: client.query.builder(Account)
                .select(Account.name)
                .expand(tasks_opt)
                .top(3)
                .execute()
            )
        )
        print(f"[OK] Found {len(accounts)} accounts with nested task expansion:")
        for acc in accounts:
            # Account_Tasks is a FieldDescriptor that captures the expanded collection.
            tasks = acc.Account_Tasks or []
            print(f"  - '{acc.name}' has {len(tasks)} task(s)")
            for task in tasks:
                print(f"      - {task.get('subject')}")
    except Exception as e:  # noqa: BLE001
        print(f"[SKIP] Nested expand demo skipped: {e}")

    # ============================================================================
    # 9. SQL QUERY
    # ============================================================================
    print("\n" + "=" * 80)
    print("9. SQL Query")
    print("=" * 80)

    # SQL is string-based — unchanged. Results are Record objects (dict-like).
    log_call("client.query.sql('SELECT new_title, new_quantity FROM new_walkthroughdemo WHERE ...')")
    sql = "SELECT new_title, new_quantity FROM new_walkthroughdemo WHERE new_completed = 1"
    try:
        results = backoff(lambda: client.query.sql(sql))
        print(f"[OK] SQL query returned {len(results)} completed records:")
        for result in results[:5]:
            print(f"  - new_title='{result.get('new_title')}', new_quantity={result.get('new_quantity')}")
    except Exception as e:
        print(f"[WARN] SQL query failed (known server-side bug): {str(e)}")

    # ============================================================================
    # 10. PICKLIST LABEL CONVERSION
    # ============================================================================
    print("\n" + "=" * 80)
    print("10. Picklist Label Conversion")
    print("=" * 80)

    log_call("client.records.create(WalkthroughDemo(new_priority='High'))")
    label_id = backoff(lambda: client.records.create(
        WalkthroughDemo(
            new_title="Test label conversion",
            new_quantity=1,
            new_amount=99.99,
            new_completed=False,
            new_priority="High",   # string label — SDK resolves to int
        )
    ))
    retrieved_record = backoff(lambda: client.records.get(WalkthroughDemo, label_id))
    retrieved = WalkthroughDemo.from_record(retrieved_record)
    print("[OK] Created record with string label 'High' for new_priority")
    print(f"  new_priority stored as integer: {retrieved.new_priority}")
    print(f"  new_priority@FormattedValue: {retrieved_record.get('new_priority@OData.Community.Display.V1.FormattedValue')}")

    log_call("client.records.update(WalkthroughDemo, label_id, WalkthroughDemo(new_priority='Low'))")
    backoff(lambda: client.records.update(WalkthroughDemo, label_id, WalkthroughDemo(new_priority="Low")))
    updated_label_record = backoff(lambda: client.records.get(WalkthroughDemo, label_id))
    updated_label = WalkthroughDemo.from_record(updated_label_record)
    print("[OK] Updated record with string label 'Low' for new_priority")
    print(f"  new_priority stored as integer: {updated_label.new_priority}")
    print(f"  new_priority@FormattedValue: {updated_label_record.get('new_priority@OData.Community.Display.V1.FormattedValue')}")

    # ============================================================================
    # 11. COLUMN MANAGEMENT
    # ============================================================================
    print("\n" + "=" * 80)
    print("11. Column Management")
    print("=" * 80)

    # Column management is schema-level work — unchanged from the string-based API.
    log_call("client.tables.add_columns(WalkthroughDemo, {'new_Tags': 'string'})")
    created_cols = backoff(lambda: client.tables.add_columns(WalkthroughDemo, {"new_Tags": "string"}))
    print(f"[OK] Added column: {created_cols[0]}")

    log_call("client.tables.remove_columns(WalkthroughDemo, ['new_Tags'])")
    backoff(lambda: client.tables.remove_columns(WalkthroughDemo, ["new_Tags"]))
    print("[OK] Deleted column: new_Tags")

    # ============================================================================
    # 12. DELETE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("12. Delete Operations")
    print("=" * 80)

    log_call(f"client.records.delete(WalkthroughDemo, id1)")
    backoff(lambda: client.records.delete(WalkthroughDemo, id1))
    print(f"[OK] Deleted single record: {id1}")

    log_call(f"client.records.delete(WalkthroughDemo, [{len(paging_ids)} IDs])")
    job_id = backoff(lambda: client.records.delete(WalkthroughDemo, paging_ids))
    print(f"[OK] Bulk delete job started: {job_id}")
    print(f"  (Deleting {len(paging_ids)} paging demo records)")

    # ============================================================================
    # 13. BATCH OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("13. Batch Operations")
    print("=" * 80)

    # Batch create using entity instances — validated payloads in one HTTP request
    log_call("client.batch.new() + batch.records.create(WalkthroughDemo(...)) x2")
    batch = client.batch.new()
    batch.records.create(WalkthroughDemo, WalkthroughDemo(
        new_title="Batch task alpha",
        new_quantity=1,
        new_amount=25.0,
        new_completed=False,
        new_priority=Priority.LOW,
    ))
    batch.records.create(WalkthroughDemo, WalkthroughDemo(
        new_title="Batch task beta",
        new_quantity=2,
        new_amount=50.0,
        new_completed=False,
        new_priority=Priority.MEDIUM,
    ))
    result = batch.execute()
    batch_ids = list(result.entity_ids)
    print(f"[OK] Batch create: {len(result.succeeded)} operations in one HTTP request, {len(batch_ids)} records created")

    # Batch get: read both records in a single request
    log_call("client.batch.new() + batch.records.get(...) x2 + batch.execute()")
    batch = client.batch.new()
    for bid in batch_ids:
        batch.records.get(WalkthroughDemo, bid, select=[WalkthroughDemo.new_title.name, WalkthroughDemo.new_quantity.name])
    result = batch.execute()
    print(f"[OK] Batch get: {len(result.succeeded)} reads in one HTTP request")
    for resp in result.succeeded:
        if resp.data:
            print(f"  new_title='{resp.data.get('new_title')}', new_quantity={resp.data.get('new_quantity')}")

    # Changeset: create + update atomically (all-or-nothing)
    log_call("with batch.changeset() as cs: cs.records.create(...); cs.records.update(cs_ref, ...)")
    batch = client.batch.new()
    with batch.changeset() as cs:
        cs_ref = cs.records.create(WalkthroughDemo, WalkthroughDemo(
            new_title="Changeset task",
            new_quantity=5,
            new_amount=100.0,
            new_completed=False,
            new_priority=Priority.HIGH,
        ))
        cs.records.update(WalkthroughDemo, cs_ref, WalkthroughDemo(new_completed=True))
    result = batch.execute()
    if not result.has_errors:
        batch_ids.extend(result.entity_ids)
        print(f"[OK] Changeset: {len(result.succeeded)} operations committed atomically")
    else:
        for item in result.failed:
            print(f"[WARN] Changeset error {item.status_code}: {item.error_message}")

    # Batch delete: clean up all batch-created records in one request
    log_call(f"client.batch.new() + batch.records.delete(...) x{len(batch_ids)} + batch.execute()")
    batch = client.batch.new()
    for bid in batch_ids:
        batch.records.delete(WalkthroughDemo, bid)
    result = batch.execute(continue_on_error=True)
    print(f"[OK] Batch delete: {len(result.succeeded)} records deleted in one HTTP request")

    # ============================================================================
    # 14. CLEANUP
    # ============================================================================
    print("\n" + "=" * 80)
    print("14. Cleanup")
    print("=" * 80)

    log_call("client.tables.delete(WalkthroughDemo)")
    try:
        backoff(lambda: client.tables.delete(WalkthroughDemo))
        print(f"[OK] Deleted table: {WalkthroughDemo.__table__}")
    except MetadataError as ex:
        if "not found" in str(ex).lower():
            print(f"[OK] Table already removed: {WalkthroughDemo.__table__}")
        else:
            raise
    except Exception as ex:  # noqa: BLE001
        code = getattr(getattr(ex, "response", None), "status_code", None)
        if isinstance(ex, requests.exceptions.HTTPError) and code == 404:
            print(f"[OK] Table removed: {WalkthroughDemo.__table__}")
        else:
            raise

    # ============================================================================
    # SUMMARY
    # ============================================================================
    print("\n" + "=" * 80)
    print("Typed Walkthrough Complete!")
    print("=" * 80)
    print("\nDemonstrated operations:")
    print("  [OK] Entity class definition (WalkthroughDemo, Account)")
    print("  [OK] Table creation with multiple column types")
    print("  [OK] Single and multiple record creation using WalkthroughDemo(...)")
    print("  [OK] Typed attribute access on query results (demo.new_title vs record.get())")
    print("  [OK] Single and multiple record updates using WalkthroughDemo(...)")
    print("  [OK] Paging through large result sets with typed builder")
    print("  [OK] Typed QueryBuilder (typed select, where, order_by, in_(), between(), &, |)")
    print("  [OK] to_dataframe() with typed conditions")
    print("  [OK] Expand navigation properties (typed Account builder)")
    print("  [OK] SQL queries (string-based, unchanged)")
    print("  [OK] Picklist label-to-value conversion with WalkthroughDemo(...)")
    print("  [OK] Column management (unchanged)")
    print("  [OK] Single and bulk delete operations")
    print("  [OK] Batch operations with WalkthroughDemo(...) instances")
    print("  [OK] Table cleanup")
    print("=" * 80)


if __name__ == "__main__":
    main()
