# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
Walkthrough demonstrating core Dataverse SDK operations using strongly typed entities.

This is the typed counterpart to walkthrough.py.  Every section performs the
same operations as the original — the only difference is how those operations
are expressed:

  String-based (original)           Typed (this file)
  ─────────────────────────────     ──────────────────────────────────────────
  builder("new_WalkthroughDemo")    builder(WalkthroughDemo)
  .select("new_Title", ...)         .select(WalkthroughDemo.new_title, ...)
  .filter_eq("new_Completed", 0)    .where(WalkthroughDemo.new_completed == False)
  record.get("new_title")           demo.new_title
  {"new_Title": "x", ...}           WalkthroughDemo(new_title="x", ...)

Under the hood both paths compile to identical OData requests.  No changes
were made to the HTTP layer, auth, or data layer.

This example shows:
- Defining a typed entity class that mirrors a Dataverse table
- Single and multiple record CRUD using WalkthroughDemo(...)
- Typed attribute access on query results (demo.new_title vs record.get())
- Querying with typed field expressions (WalkthroughDemo.statecode == 0)
- Composable typed filter conditions (&, |, ~)
- Paging, to_dataframe(), expand, SQL, batch — all still work unchanged

Prerequisites:
- pip install PowerPlatform-Dataverse-Client
- pip install azure-identity
"""

import argparse
import json
import time
from enum import IntEnum
from azure.identity import InteractiveBrowserCredential
from PowerPlatform.Dataverse.client import DataverseClient
from PowerPlatform.Dataverse.core.errors import MetadataError
from PowerPlatform.Dataverse.models.entity import Entity, Field, NavField
from PowerPlatform.Dataverse.generator import generate
import requests


# Simple logging helper
def log_call(description):
    print(f"\n-> {description}")


# Define enum for priority picklist
class Priority(IntEnum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3


# ---------------------------------------------------------------------------
# Typed entity classes
#
# These mirror the Dataverse tables used in this walkthrough.
# In a real project these would be auto-generated by the generate() tool.
# Field names are the OData logical names (lowercase).
# ---------------------------------------------------------------------------

class WalkthroughDemo(Entity, table="new_WalkthroughDemo", primary_key="new_walkthroughdemoid"):
    """Typed entity for the new_WalkthroughDemo custom table.

    Explicit Field calls carry schema_name (for table creation) and
    dataverse_type (for column type mapping), so the entity class is the single
    source of truth for both query-time and metadata-creation operations.
    """
    # Primary key — no dataverse_type; Dataverse manages this column automatically.
    new_walkthroughdemoid = Field("new_walkthroughdemoid", str)
    # Data columns — schema_name is the PascalCase variant used in metadata APIs.
    new_title     = Field("new_title",     str,   schema_name="new_Title",     dataverse_type="string")
    new_quantity  = Field("new_quantity",  int,   schema_name="new_Quantity",  dataverse_type="int")
    new_amount    = Field("new_amount",    float, schema_name="new_Amount",    dataverse_type="decimal")
    new_completed = Field("new_completed", bool,  schema_name="new_Completed", dataverse_type="bool")
    new_notes     = Field("new_notes",     str,   schema_name="new_Notes",     dataverse_type="memo")
    new_priority  = Field("new_priority",  int,   schema_name="new_Priority",  dataverse_type=Priority)


class Task(Entity, table="task", primary_key="activityid"):
    """Typed entity for the built-in task table (used in nested expand demo)."""
    activityid  = Field("activityid",  str)
    subject     = Field("subject",     str)
    createdon   = Field("createdon",   str)
    statecode   = Field("statecode",   int)


class Account(Entity, table="account", primary_key="accountid"):
    """Typed entity for the built-in account table (used in expand demo)."""
    accountid = Field("accountid", str)
    name      = Field("name",      str)
    # Navigation properties — typed with NavField; appear on instances after expand.
    primarycontactid = NavField("primarycontactid")   # single-value lookup
    Account_Tasks    = NavField("Account_Tasks")       # collection


def backoff(op, *, delays=(0, 2, 5, 10, 20, 20)):
    last = None
    total_delay = 0
    attempts = 0
    for d in delays:
        if d:
            time.sleep(d)
            total_delay += d
        attempts += 1
        try:
            result = op()
            if attempts > 1:
                retry_count = attempts - 1
                print(f"   [INFO] Backoff succeeded after {retry_count} retry(s); waited {total_delay}s total.")
            return result
        except Exception as ex:  # noqa: BLE001
            last = ex
            continue
    if last:
        if attempts:
            retry_count = max(attempts - 1, 0)
            print(f"   [WARN] Backoff exhausted after {retry_count} retry(s); waited {total_delay}s total.")
        raise last


def main():
    print("=" * 80)
    print("Dataverse SDK Walkthrough — Strongly Typed")
    print("=" * 80)

    # ============================================================================
    # 1. SETUP & AUTHENTICATION
    # ============================================================================
    print("\n" + "=" * 80)
    print("1. Setup & Authentication")
    print("=" * 80)

    parser = argparse.ArgumentParser(description="Typed Dataverse SDK walkthrough")
    parser.add_argument("--url", required=True, help="Dataverse org URL (e.g. https://yourorg.crm.dynamics.com)")
    args = parser.parse_args()
    base_url = args.url.rstrip("/")

    log_call("InteractiveBrowserCredential()")
    credential = InteractiveBrowserCredential()

    log_call(f"DataverseClient(base_url='{base_url}', credential=...)")
    with DataverseClient(base_url=base_url, credential=credential) as client:
        print(f"[OK] Connected to: {base_url}")
        _run_walkthrough(client)


def _run_walkthrough(client):
    # ============================================================================
    # 2. GENERATE ENTITY CLASSES
    # ============================================================================
    # The generator introspects the live environment and writes typed Python
    # entity files.  You run it once (or in CI), commit the Types/ folder, and
    # import the classes everywhere else in your project:
    #
    #   from Types import Account, Contact
    #
    # This section runs the generator live, previews the output, then immediately
    # imports the generated Account class and uses it in a real query — so you
    # can see the full round-trip in one place.
    # ============================================================================
    print("\n" + "=" * 80)
    print("2. Entity Class Generator")
    print("=" * 80)

    import os
    import sys
    import importlib
    import importlib.util

    TYPES_DIR = "Types_demo"

    log_call(f'generate(client, entities=["account"], output_dir="{TYPES_DIR}/")')
    written = generate(
        client,
        entities=["account"],
        output_dir=TYPES_DIR,
        verbose=True,
    )
    print(f"[OK] Generator wrote {len(written)} file(s):")
    for path in written:
        print(f"  {path}")

    # ------------------------------------------------------------------
    # Preview the generated source
    # ------------------------------------------------------------------
    account_path = os.path.join(TYPES_DIR, "account.py")
    if os.path.exists(account_path):
        with open(account_path, encoding="utf-8") as fh:
            preview_lines = fh.readlines()[:30]
        print(f"\n[Preview: {account_path} (first 30 lines)]")
        print("".join(preview_lines))

    # ------------------------------------------------------------------
    # Import the generated class and use it in a real query
    # ------------------------------------------------------------------
    # Add the Types_demo directory to sys.path so Python can find it.
    types_abs = os.path.abspath(TYPES_DIR)
    if types_abs not in sys.path:
        sys.path.insert(0, os.path.abspath(os.path.dirname(TYPES_DIR)))

    # Dynamically import — in a real project this would be a normal top-level
    # import: ``from Types import Account``
    spec = importlib.util.spec_from_file_location("Types_demo.account", account_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    GeneratedAccount = mod.Account

    print(f"\n[OK] Imported generated class: {GeneratedAccount}")
    print(f"     table        = {GeneratedAccount.__table__!r}")
    print(f"     primary_key  = {GeneratedAccount.__primary_key__!r}")
    print(f"     fields       = {[f for f in vars(GeneratedAccount) if not f.startswith('_')]}")

    # Run a real query using the generated class — identical to using a hand-
    # written entity class.  No SDK changes needed; generate() output is a
    # drop-in replacement.
    log_call("client.query.builder(GeneratedAccount).select(GeneratedAccount.name).top(3).execute()")
    rows = list(
        client.query.builder(GeneratedAccount)
        .select(GeneratedAccount.name)
        .where(GeneratedAccount.statecode == 0)
        .top(3)
        .execute()
    )
    print(f"[OK] Query returned {len(rows)} account(s) using generated class:")
    for row in rows:
        # Use typed attribute access — works exactly like a hand-written class.
        acct = GeneratedAccount.from_record(row)
        print(f"  name={acct.name!r}")

    # ============================================================================
    # 3. TABLE CREATION (METADATA)
    # ============================================================================
    print("\n" + "=" * 80)
    print("3. Table Creation (Metadata)")
    print("=" * 80)

    # Pass the entity class directly — the SDK resolves WalkthroughDemo.__table__
    # internally, so there's no need to reference the string name at all.
    log_call("client.tables.get(WalkthroughDemo)")
    table_info = backoff(lambda: client.tables.get(WalkthroughDemo))

    if table_info:
        print(f"[OK] Table already exists: {table_info.schema_name}")
        print(f"  Logical Name: {table_info.logical_name}")
        print(f"  Entity Set: {table_info.entity_set_name}")
    else:
        # columns are derived automatically from WalkthroughDemo.columns_schema()
        # because every Field carries schema_name and dataverse_type.
        log_call("client.tables.create(WalkthroughDemo)  # no columns dict needed")
        table_info = backoff(lambda: client.tables.create(WalkthroughDemo))
        print(f"[OK] Created table: {table_info.schema_name}")
        print(f"  Columns created: {', '.join(table_info.columns_created or [])}")

    # ============================================================================
    # 4. DEFAULT VALUES — COLUMN CREATION AND ROW CREATION
    # ============================================================================
    # Verify what Dataverse actually stored for column constraints (e.g. MaxLength,
    # MinValue) and what values unspecified fields receive on a new record.
    # ============================================================================
    print("\n" + "=" * 80)
    print("4. Default Values — Column and Row")
    print("=" * 80)

    # --- Part A: column-level defaults ----------------------------------------
    # Fetch attribute metadata for a representative set of columns and print the
    # type-specific constraints Dataverse stored.  SDK sends these values during
    # table creation; this confirms what the backend actually persisted.
    print("\n[Part A] Column-level defaults (constraints stored by Dataverse)")

    odata = client._get_odata()
    meta_id = table_info.metadata_id

    # Fetch without $select so Dataverse returns all properties for the concrete
    # derived type (MaxLength on StringAttributeMetadata, MinValue/MaxValue on
    # IntegerAttributeMetadata, etc.).  Using $select on the base collection
    # only allows base-type properties and rejects type-specific ones.
    def _fetch_attr_full(col_name):
        url = f"{odata.api}/EntityDefinitions({meta_id})/Attributes"
        escaped = odata._escape_odata_quotes(col_name.lower())
        r = odata._request("get", url, params={"$filter": f"LogicalName eq '{escaped}'"})
        items = r.json().get("value", [])
        return items[0] if items else None

    column_checks = [
        "new_title",
        "new_quantity",
        "new_amount",
        "new_completed",
        "new_notes",
    ]

    for col_name in column_checks:
        attr = backoff(lambda c=col_name: _fetch_attr_full(c))
        if attr:
            summary = {
                k: attr[k]
                for k in ("AttributeType", "MaxLength", "MinValue", "MaxValue",
                          "Precision", "Format", "RequiredLevel")
                if k in attr
            }
            # RequiredLevel is a nested dict — flatten to its Value string
            if "RequiredLevel" in summary and isinstance(summary["RequiredLevel"], dict):
                summary["RequiredLevel"] = summary["RequiredLevel"].get("Value")
            print(f"  {col_name}: {json.dumps(summary)}")
        else:
            print(f"  {col_name}: (not found)")

    # --- Part B: row-level defaults --------------------------------------------
    # Create a record with ONLY new_title set.  Retrieve it with all WalkthroughDemo
    # fields selected and print every value — unspecified fields should be null.
    print("\n[Part B] Row-level defaults (unspecified fields on a new record)")

    log_call("client.records.create(WalkthroughDemo(new_title='Defaults test'))  # only title set")
    defaults_id = backoff(lambda: client.records.create(
        WalkthroughDemo(new_title="Defaults test")
    ))
    print(f"[OK] Created record: {defaults_id}")

    log_call("client.records.get(WalkthroughDemo, defaults_id)  # retrieve all fields")
    defaults_demo = backoff(lambda: client.records.get(WalkthroughDemo, defaults_id))
    print("[OK] All field values on the new record:")
    print(
        json.dumps(
            {
                "new_walkthroughdemoid": defaults_demo.new_walkthroughdemoid,
                "new_title":            defaults_demo.new_title,
                "new_quantity":         defaults_demo.new_quantity,
                "new_amount":           defaults_demo.new_amount,
                "new_completed":        defaults_demo.new_completed,
                "new_notes":            defaults_demo.new_notes,
                "new_priority":         defaults_demo.new_priority,
            },
            indent=2,
        )
    )

    # Clean up the defaults test record before continuing
    client.records.delete(WalkthroughDemo, defaults_id)
    print(f"[OK] Cleaned up defaults test record: {defaults_id}")

    # ============================================================================
    # 5. CREATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("5. Create Operations")
    print("=" * 80)

    # Pass a WalkthroughDemo instance — table is inferred, field names validated.
    log_call("client.records.create(WalkthroughDemo(...))")
    id1 = backoff(lambda: client.records.create(
        WalkthroughDemo(
            new_title="Complete project documentation",
            new_quantity=5,
            new_amount=1250.50,
            new_completed=False,
            new_notes="This is a multiline memo field.\nIt supports longer text content.",
            new_priority=Priority.MEDIUM,
        )
    ))
    print(f"[OK] Created single record: {id1}")

    log_call("client.records.create([WalkthroughDemo(...), ...])")
    ids = backoff(lambda: client.records.create(
        [
            WalkthroughDemo(
                new_title="Review code changes",
                new_quantity=10,
                new_amount=500.00,
                new_completed=True,
                new_priority=Priority.HIGH,
            ),
            WalkthroughDemo(
                new_title="Update test cases",
                new_quantity=8,
                new_amount=750.25,
                new_completed=False,
                new_priority=Priority.LOW,
            ),
            WalkthroughDemo(
                new_title="Deploy to staging",
                new_quantity=3,
                new_amount=2000.00,
                new_completed=False,
                new_priority=Priority.HIGH,
            ),
        ]
    ))
    print(f"[OK] Created {len(ids)} records: {ids}")

    # ============================================================================
    # 6. READ OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("6. Read Operations")
    print("=" * 80)

    # Single read by ID — returns a WalkthroughDemo instance directly
    # because an Entity class was passed (no manual from_record() needed).
    log_call("client.records.get(WalkthroughDemo, id1)  →  WalkthroughDemo instance")
    demo = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    print("[OK] Retrieved single record (typed attribute access):")
    print(
        json.dumps(
            {
                "new_walkthroughdemoid": demo.new_walkthroughdemoid,
                "new_title":            demo.new_title,
                "new_quantity":         demo.new_quantity,
                "new_amount":           demo.new_amount,
                "new_completed":        demo.new_completed,
                "new_notes":            demo.new_notes,
                "new_priority":         demo.new_priority,
            },
            indent=2,
        )
    )

    # Multiple read with typed filter expression.
    # WalkthroughDemo.new_quantity > 5  produces FilterExpression("new_quantity gt 5")
    log_call("client.query.builder(WalkthroughDemo).where(WalkthroughDemo.new_quantity > 5).execute()")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
            .where(WalkthroughDemo.new_quantity > 5)
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with new_quantity > 5")
    for d in demos:
        print(f"  - new_title='{d.new_title}', new_quantity={d.new_quantity}")

    # ============================================================================
    # 7. UPDATE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("7. Update Operations")
    print("=" * 80)

    log_call("client.records.update(WalkthroughDemo, id1, WalkthroughDemo(...))")
    backoff(lambda: client.records.update(
        WalkthroughDemo,
        id1,
        WalkthroughDemo(
            new_quantity=100,
            new_notes="Updated memo field.\nNow with revised content across multiple lines.",
        ),
    ))
    updated = backoff(lambda: client.records.get(WalkthroughDemo, id1))
    print(f"[OK] Updated single record new_quantity: {updated.new_quantity}")
    print(f"  new_notes: {repr(updated.new_notes)}")

    # Broadcast same change to all ids
    log_call(f"client.records.update(WalkthroughDemo, [{len(ids)} IDs], WalkthroughDemo(...))")
    backoff(lambda: client.records.update(WalkthroughDemo, ids, WalkthroughDemo(new_completed=True)))
    print(f"[OK] Updated {len(ids)} records to new_completed=True")

    # ============================================================================
    # 8. PAGING DEMO
    # ============================================================================
    print("\n" + "=" * 80)
    print("8. Paging Demo")
    print("=" * 80)

    log_call("client.records.create([20 × WalkthroughDemo(...)])")
    paging_records = [
        WalkthroughDemo(
            new_title=f"Paging test item {i}",
            new_quantity=i,
            new_amount=i * 10.0,
            new_completed=False,
            new_priority=Priority.LOW,
        )
        for i in range(1, 21)
    ]
    paging_ids = backoff(lambda: client.records.create(paging_records))
    print(f"[OK] Created {len(paging_ids)} records for paging demo")

    # Typed builder with page_size — results are WalkthroughDemo instances
    log_call("client.query.builder(WalkthroughDemo).order_by(WalkthroughDemo.new_quantity).page_size(5).execute(by_page=True)")
    print("Fetching records with page_size=5...")
    for page_num, page in enumerate(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_walkthroughdemoid, WalkthroughDemo.new_quantity)
            .order_by(WalkthroughDemo.new_quantity)
            .page_size(5)
            .execute(by_page=True)
        ),
        start=1,
    ):
        record_ids = [d.new_walkthroughdemoid[:8] + "..." for d in page]
        print(f"  Page {page_num}: {len(page)} records - IDs: {record_ids}")

    # ============================================================================
    # 9. QUERYBUILDER — TYPED FLUENT QUERIES
    # ============================================================================
    print("\n" + "=" * 80)
    print("9. QueryBuilder — Typed Fluent Queries")
    print("=" * 80)

    # Basic typed query: field descriptors in select, typed condition in where
    log_call("client.query.builder(WalkthroughDemo).select(fields).where(expr).order_by(field).execute()")
    print("Querying incomplete records ordered by amount (typed builder)...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount, WalkthroughDemo.new_priority)
            .where(WalkthroughDemo.new_completed == False)
            .order_by(WalkthroughDemo.new_amount, descending=True)
            .top(10)
            .execute()
        )
    )
    print(f"[OK] Typed query found {len(demos)} incomplete records:")
    for d in demos[:5]:
        print(f"  - '{d.new_title}' amount={d.new_amount}")

    # in_() method on a Field
    log_call("WalkthroughDemo.new_priority.in_([Priority.HIGH, Priority.LOW])")
    print("Querying records with HIGH or LOW priority (typed in_())...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_priority)
            .where(WalkthroughDemo.new_priority.in_([Priority.HIGH, Priority.LOW]))
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with HIGH or LOW priority")
    for d in demos[:5]:
        print(f"  - '{d.new_title}' priority={d.new_priority}")

    # between() method on a Field
    log_call("WalkthroughDemo.new_amount.between(500, 1500)")
    print("Querying records with amount between 500 and 1500 (typed between())...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount)
            .where(WalkthroughDemo.new_amount.between(500, 1500))
            .execute()
        )
    )
    print(f"[OK] Found {len(demos)} records with amount in [500, 1500]")
    for d in demos:
        print(f"  - '{d.new_title}' amount={d.new_amount}")

    # & operator composes two typed conditions into a single AND expression
    log_call("(WalkthroughDemo.new_completed == False) & (WalkthroughDemo.new_amount > 100)")
    print("Querying with typed AND expression...")
    demos = list(
        backoff(
            lambda: client.query.builder(WalkthroughDemo)
            .select(WalkthroughDemo.new_title, WalkthroughDemo.new_amount, WalkthroughDemo.new_quantity)
            .where(
                (WalkthroughDemo.new_completed == False)
                & (WalkthroughDemo.new_amount > 100)
            )
            .order_by(WalkthroughDemo.new_amount, descending=True)
            .top(5)
            .execute()
        )
    )
    print(f"[OK] AND expression found {len(demos)} records:")
    for d in demos:
        print(f"  - '{d.new_title}' amount={d.new_amount} qty={d.new_quantity}")

    # Multiple where() calls AND-joined + between() + paged (by_page=True)
    log_call("Multiple .where() calls + .between() + paging")
    print("Querying with combined typed filters and paging...")
    combined_page_count = 0
    combined_record_count = 0
    for page in backoff(
        lambda: client.query.builder(WalkthroughDemo)
        .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
        .where(WalkthroughDemo.new_completed == False)
        .where(WalkthroughDemo.new_quantity.between(1, 15))
        .order_by(WalkthroughDemo.new_quantity)
        .page_size(3)
        .execute(by_page=True)
    ):
        combined_page_count += 1
        combined_record_count += len(page)
        titles = [d.new_title for d in page]
        print(f"  Page {combined_page_count}: {len(page)} records - {titles}")
    print(f"[OK] Combined query: {combined_record_count} records across {combined_page_count} page(s)")

    # to_dataframe() — returns a pandas DataFrame (inherently untyped, unchanged)
    log_call("client.query.builder(WalkthroughDemo).where(...).to_dataframe()")
    print("Querying completed records as a pandas DataFrame (to_dataframe)...")
    df = backoff(
        lambda: client.query.builder(WalkthroughDemo)
        .select(WalkthroughDemo.new_title, WalkthroughDemo.new_quantity)
        .where(WalkthroughDemo.new_completed == True)
        .to_dataframe()
    )
    print(f"[OK] to_dataframe() returned {len(df)} rows, columns: {list(df.columns)}")
    if not df.empty:
        print(f"  First row: new_title='{df.iloc[0].get('new_title')}', new_quantity={df.iloc[0].get('new_quantity')}")
        print(f"  Sum of new_quantity: {df['new_quantity'].sum()}")
    else:
        print("  (empty DataFrame)")

    # ============================================================================
    # 10. EXPAND (NAVIGATION PROPERTIES)
    # ============================================================================
    print("\n" + "=" * 80)
    print("10. Expand (Navigation Properties)")
    print("=" * 80)

    # Simple expand — pass NavField directly (no string needed)
    log_call("client.query.builder(Account).select(Account.name).expand(Account.primarycontactid).top(3).execute()")
    print("Querying accounts with primary contact expanded...")
    try:
        accounts = list(
            backoff(
                lambda: client.query.builder(Account)
                .select(Account.name)
                .expand(Account.primarycontactid)
                .top(3)
                .execute()
            )
        )
        print(f"[OK] Found {len(accounts)} accounts with expanded contact:")
        for acc in accounts:
            # NavField value on instance: raw dict from server (or None if not expanded)
            contact = acc.primarycontactid
            contact_name = contact.get("fullname", "(none)") if contact else "(no contact)"
            print(f"  - '{acc.name}' -> Contact: {contact_name}")
    except Exception as e:  # noqa: BLE001
        print(f"[SKIP] Expand demo skipped (no accounts in org): {e}")

    # Nested expand via NavField fluent methods — no ExpandOption import needed
    log_call("Account.Account_Tasks.select(...).order_by(...).top(3)  →  ExpandOption")
    print("Querying accounts with nested expand options on tasks...")
    try:
        accounts = list(
            backoff(
                lambda: client.query.builder(Account)
                .select(Account.name)
                .expand(
                    Account.Account_Tasks
                    .select(Task.subject, Task.createdon)
                    .order_by(Task.createdon, descending=True)
                    .top(3)
                )
                .top(3)
                .execute()
            )
        )
        print(f"[OK] Found {len(accounts)} accounts with nested task expansion:")
        for acc in accounts:
            tasks = acc.Account_Tasks or []
            print(f"  - '{acc.name}' has {len(tasks)} task(s)")
            for task in tasks:
                print(f"      - {task.get('subject')}")
    except Exception as e:  # noqa: BLE001
        print(f"[SKIP] Nested expand demo skipped: {e}")

    # ============================================================================
    # 11. SQL QUERY
    # ============================================================================
    print("\n" + "=" * 80)
    print("11. SQL Query")
    print("=" * 80)

    # SQL is string-based — unchanged. Results are Record objects (dict-like).
    log_call("client.query.sql('SELECT new_title, new_quantity FROM new_walkthroughdemo WHERE ...')")
    sql = "SELECT new_title, new_quantity FROM new_walkthroughdemo WHERE new_completed = 1"
    try:
        results = backoff(lambda: client.query.sql(sql))
        print(f"[OK] SQL query returned {len(results)} completed records:")
        for result in results[:5]:
            print(f"  - new_title='{result.get('new_title')}', new_quantity={result.get('new_quantity')}")
    except Exception as e:
        print(f"[WARN] SQL query failed (known server-side bug): {str(e)}")

    # ============================================================================
    # 12. PICKLIST LABEL CONVERSION
    # ============================================================================
    print("\n" + "=" * 80)
    print("12. Picklist Label Conversion")
    print("=" * 80)

    log_call("client.records.create(WalkthroughDemo(new_priority='High'))")
    label_id = backoff(lambda: client.records.create(
        WalkthroughDemo(
            new_title="Test label conversion",
            new_quantity=1,
            new_amount=99.99,
            new_completed=False,
            new_priority="High",   # string label — SDK resolves to int
        )
    ))
    retrieved = backoff(lambda: client.records.get(WalkthroughDemo, label_id))
    print("[OK] Created record with string label 'High' for new_priority")
    print(f"  new_priority stored as integer: {retrieved.new_priority}")

    log_call("client.records.update(WalkthroughDemo, label_id, WalkthroughDemo(new_priority='Low'))")
    backoff(lambda: client.records.update(WalkthroughDemo, label_id, WalkthroughDemo(new_priority="Low")))
    updated_label = backoff(lambda: client.records.get(WalkthroughDemo, label_id))
    print("[OK] Updated record with string label 'Low' for new_priority")
    print(f"  new_priority stored as integer: {updated_label.new_priority}")

    # ============================================================================
    # 13. COLUMN MANAGEMENT
    # ============================================================================
    print("\n" + "=" * 80)
    print("13. Column Management")
    print("=" * 80)

    # Column management is schema-level work — unchanged from the string-based API.
    log_call("client.tables.add_columns(WalkthroughDemo, {'new_Tags': 'string'})")
    created_cols = backoff(lambda: client.tables.add_columns(WalkthroughDemo, {"new_Tags": "string"}))
    print(f"[OK] Added column: {created_cols[0]}")

    log_call("client.tables.remove_columns(WalkthroughDemo, ['new_Tags'])")
    backoff(lambda: client.tables.remove_columns(WalkthroughDemo, ["new_Tags"]))
    print("[OK] Deleted column: new_Tags")

    # ============================================================================
    # 14. DELETE OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("14. Delete Operations")
    print("=" * 80)

    log_call(f"client.records.delete(WalkthroughDemo, id1)")
    backoff(lambda: client.records.delete(WalkthroughDemo, id1))
    print(f"[OK] Deleted single record: {id1}")

    log_call(f"client.records.delete(WalkthroughDemo, [{len(paging_ids)} IDs])")
    job_id = backoff(lambda: client.records.delete(WalkthroughDemo, paging_ids))
    print(f"[OK] Bulk delete job started: {job_id}")
    print(f"  (Deleting {len(paging_ids)} paging demo records)")

    # ============================================================================
    # 15. BATCH OPERATIONS
    # ============================================================================
    print("\n" + "=" * 80)
    print("15. Batch Operations")
    print("=" * 80)

    # Batch create using entity instances — validated payloads in one HTTP request
    log_call("client.batch.new() + batch.records.create(WalkthroughDemo(...)) x2")
    batch = client.batch.new()
    batch.records.create(WalkthroughDemo, WalkthroughDemo(
        new_title="Batch task alpha",
        new_quantity=1,
        new_amount=25.0,
        new_completed=False,
        new_priority=Priority.LOW,
    ))
    batch.records.create(WalkthroughDemo, WalkthroughDemo(
        new_title="Batch task beta",
        new_quantity=2,
        new_amount=50.0,
        new_completed=False,
        new_priority=Priority.MEDIUM,
    ))
    result = batch.execute()
    batch_ids = list(result.entity_ids)
    print(f"[OK] Batch create: {len(result.succeeded)} operations in one HTTP request, {len(batch_ids)} records created")

    # Batch get: read both records in a single request
    log_call("client.batch.new() + batch.records.get(...) x2 + batch.execute()")
    batch = client.batch.new()
    for bid in batch_ids:
        batch.records.get(WalkthroughDemo, bid, select=[WalkthroughDemo.new_title, WalkthroughDemo.new_quantity])
    result = batch.execute()
    print(f"[OK] Batch get: {len(result.succeeded)} reads in one HTTP request")
    for resp in result.succeeded:
        if resp.data:
            print(f"  new_title='{resp.data.get('new_title')}', new_quantity={resp.data.get('new_quantity')}")

    # Changeset: create + update atomically (all-or-nothing)
    log_call("with batch.changeset() as cs: cs.records.create(...); cs.records.update(cs_ref, ...)")
    batch = client.batch.new()
    with batch.changeset() as cs:
        cs_ref = cs.records.create(WalkthroughDemo, WalkthroughDemo(
            new_title="Changeset task",
            new_quantity=5,
            new_amount=100.0,
            new_completed=False,
            new_priority=Priority.HIGH,
        ))
        cs.records.update(WalkthroughDemo, cs_ref, WalkthroughDemo(new_completed=True))
    result = batch.execute()
    if not result.has_errors:
        batch_ids.extend(result.entity_ids)
        print(f"[OK] Changeset: {len(result.succeeded)} operations committed atomically")
    else:
        for item in result.failed:
            print(f"[WARN] Changeset error {item.status_code}: {item.error_message}")

    # Batch delete: clean up all batch-created records in one request
    log_call(f"client.batch.new() + batch.records.delete(...) x{len(batch_ids)} + batch.execute()")
    batch = client.batch.new()
    for bid in batch_ids:
        batch.records.delete(WalkthroughDemo, bid)
    result = batch.execute(continue_on_error=True)
    print(f"[OK] Batch delete: {len(result.succeeded)} records deleted in one HTTP request")

    # ============================================================================
    # 16. CLEANUP
    # ============================================================================
    print("\n" + "=" * 80)
    print("16. Cleanup")
    print("=" * 80)

    log_call("client.tables.delete(WalkthroughDemo)")
    try:
        backoff(lambda: client.tables.delete(WalkthroughDemo))
        print(f"[OK] Deleted table: {WalkthroughDemo.__table__}")
    except MetadataError as ex:
        if "not found" in str(ex).lower():
            print(f"[OK] Table already removed: {WalkthroughDemo.__table__}")
        else:
            raise
    except Exception as ex:  # noqa: BLE001
        code = getattr(getattr(ex, "response", None), "status_code", None)
        if isinstance(ex, requests.exceptions.HTTPError) and code == 404:
            print(f"[OK] Table removed: {WalkthroughDemo.__table__}")
        else:
            raise

    # ============================================================================
    # SUMMARY
    # ============================================================================
    print("\n" + "=" * 80)
    print("Typed Walkthrough Complete!")
    print("=" * 80)
    print("\nDemonstrated operations:")
    print("  [OK] Entity class definition (WalkthroughDemo, Account)")
    print("  [OK] Table creation with multiple column types")
    print("  [OK] Single and multiple record creation using WalkthroughDemo(...)")
    print("  [OK] Typed attribute access on query results (demo.new_title vs record.get())")
    print("  [OK] Single and multiple record updates using WalkthroughDemo(...)")
    print("  [OK] Paging through large result sets with typed builder")
    print("  [OK] Typed QueryBuilder (typed select, where, order_by, in_(), between(), &, |)")
    print("  [OK] to_dataframe() with typed conditions")
    print("  [OK] Expand navigation properties (typed Account builder)")
    print("  [OK] SQL queries (string-based, unchanged)")
    print("  [OK] Picklist label-to-value conversion with WalkthroughDemo(...)")
    print("  [OK] Column management (unchanged)")
    print("  [OK] Single and bulk delete operations")
    print("  [OK] Batch operations with WalkthroughDemo(...) instances")
    print("  [OK] Table cleanup")
    print("=" * 80)


if __name__ == "__main__":
    main()
